//! A viminfo-format dump of editor state, written to `<config-dir>/.zemacsinfo`
//! (i.e. `~/.zemacs/.zemacsinfo`) so that external tools — including ones that
//! already parse Vim's `~/.viminfo` — can read zemacs's recent files, marks,
//! jumplist, registers, and command/search history without any new format.
//!
//! The layout matches Vim 9.x byte-for-byte: each section has the same comment
//! header, the same human-readable lines, and the same machine-readable `|`
//! "bar lines" Vim emits. Sections zemacs has no equivalent for (expression /
//! input / debug history) are written empty, exactly as Vim does when they hold
//! nothing.
//!
//! The mapping from zemacs state to Vim's model:
//!   * File marks `'0`-`'9` ← the recent-files MRU list (newest = `'0`), with the
//!     cursor position of any matching open buffer (else line 1, col 0).
//!   * Jumplist ← the focused view's jump list (newest first).
//!   * Per-file marks (`> path` blocks) ← each open document's marks.
//!   * Command Line History ← the `:` register; Search String History ← `/`.
//!   * Registers ← the named/numbered registers (`:`/`/`/clipboard excluded).
//!
//! Vim stores a real per-entry timestamp; zemacs does not track one, so every
//! entry is stamped with the save time. Written on exit (see `Application::run`).

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use zemacs_core::coords_at_pos;
use zemacs_view::Editor;

const FILE_NAME: &str = ".zemacsinfo";

fn store_path() -> PathBuf {
    zemacs_loader::config_dir().join(FILE_NAME)
}

/// The home directory, derived from the config dir (`<home>/.zemacs`), so paths
/// can be tildified the way Vim writes them.
fn home_dir() -> Option<PathBuf> {
    zemacs_loader::config_dir()
        .parent()
        .map(|p| p.to_path_buf())
}

fn now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Build the `.zemacsinfo` content from live editor state and write it to disk.
pub fn save(editor: &Editor) {
    let body = render(editor, now(), home_dir().as_deref());
    let path = store_path();
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let _ = std::fs::write(path, body);
}

/// Render a path the way Vim writes it: a leading `~` for paths under `$HOME`.
fn tildify(path: &Path, home: Option<&Path>) -> String {
    if let Some(home) = home {
        if let Ok(rest) = path.strip_prefix(home) {
            if rest.as_os_str().is_empty() {
                return "~".to_string();
            }
            return format!("~/{}", rest.to_string_lossy());
        }
    }
    path.to_string_lossy().into_owned()
}

/// Quote a string for a `|` bar line the way Vim's `barline_writestring` does:
/// wrap in double quotes and backslash-escape `"`, `\`, newline, and carriage
/// return.
fn bar_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

fn canon(path: &Path) -> PathBuf {
    std::fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf())
}

/// A register's stored values, newest first (empty if unset).
fn register_values(editor: &Editor, name: char) -> Vec<String> {
    editor
        .registers
        .read(name, editor)
        .map(|vals| vals.map(|v| v.into_owned()).collect())
        .unwrap_or_default()
}

fn render(editor: &Editor, ts: u64, home: Option<&Path>) -> String {
    let mut out = String::new();

    // Header + version + encoding (two trailing blank lines, as Vim writes).
    out.push_str("# This viminfo file was generated by zemacs.\n");
    out.push_str("# You may edit it if you're careful!\n\n");
    out.push_str("# Viminfo version\n|1,4\n\n");
    out.push_str("# Value of 'encoding' when this file was written\n*encoding=utf-8\n\n\n");

    // hlsearch state (zemacs has no persisted toggle; report off like a fresh Vim).
    out.push_str("# hlsearch on (H) or off (h):\n~h\n");

    // Last search pattern, if any. Flags mirror Vim's default magic search.
    if let Some(pat) = editor.registers.first('/', editor) {
        if !pat.is_empty() {
            out.push_str("# Last Search Pattern:\n");
            let _ = writeln!(out, "~MSle0~/{}", pat);
        }
    }
    out.push('\n');

    // Command Line History (the `:` register), newest to oldest.
    out.push_str("# Command Line History (newest to oldest):\n");
    for entry in register_values(editor, ':') {
        let _ = writeln!(out, ":{}", entry);
        let _ = writeln!(out, "|2,0,{},,{}", ts, bar_quote(&entry));
    }
    out.push('\n');

    // Search String History (the `/` register), newest to oldest.
    out.push_str("# Search String History (newest to oldest):\n");
    for entry in register_values(editor, '/') {
        let _ = writeln!(out, "?{}", entry);
        let _ = writeln!(out, "|2,1,{},,{}", ts, bar_quote(&entry));
    }
    out.push('\n');

    // zemacs has no equivalents for these — emitted empty, exactly as Vim does.
    out.push_str("# Expression History (newest to oldest):\n\n");
    out.push_str("# Input Line History (newest to oldest):\n\n");
    out.push_str("# Debug Line History (newest to oldest):\n\n");

    // Registers — skip command/search history and the clipboard proxies.
    out.push_str("# Registers:\n");
    for name in editor.registers.written() {
        if matches!(name, ':' | '/' | '*' | '+') {
            continue;
        }
        let values = register_values(editor, name);
        // Split into physical lines so multi-line yanks render one `\t<line>` each.
        let lines: Vec<String> = values
            .iter()
            .flat_map(|v| v.split('\n'))
            .map(str::to_string)
            .collect();
        if lines.is_empty() {
            continue;
        }
        let _ = writeln!(out, "\"{}\tCHAR\t0", name);
        for line in &lines {
            let _ = writeln!(out, "\t{}", line);
        }
        let mut bar = format!("|3,0,{},0,{},0,{}", name as u32, lines.len(), ts);
        for line in &lines {
            bar.push(',');
            bar.push_str(&bar_quote(line));
        }
        out.push_str(&bar);
        out.push('\n');
    }
    out.push('\n');

    // Cursor position of every open buffer, keyed by canonical path, so file
    // marks can carry a real line/col when the file is currently open.
    let mut open_cursor: HashMap<PathBuf, (usize, usize)> = HashMap::new();
    for (view, _) in editor.tree.views() {
        if let Some(doc) = editor.document(view.doc) {
            if let Some(path) = doc.path() {
                let text = doc.text().slice(..);
                let pos = doc.selection(view.id).primary().cursor(text);
                let coords = coords_at_pos(text, pos);
                open_cursor.insert(canon(path), (coords.row + 1, coords.col));
            }
        }
    }

    // Letter/auto marks of every open buffer, keyed by canonical path, sorted by
    // mark name — folded into each file's `> path` block below.
    let mut open_marks: HashMap<PathBuf, Vec<(char, (usize, usize))>> = HashMap::new();
    for doc in editor.documents() {
        let Some(path) = doc.path() else { continue };
        let text = doc.text().slice(..);
        let mut marks: Vec<(char, (usize, usize))> = doc
            .marks_iter()
            .map(|(m, pos)| {
                let coords = coords_at_pos(text, pos);
                (m, (coords.row + 1, coords.col))
            })
            .collect();
        if marks.is_empty() {
            continue;
        }
        marks.sort_by_key(|(m, _)| *m);
        open_marks.insert(canon(path), marks);
    }

    // The recent-files MRU list (newest first) drives both the numbered file
    // marks and the per-file `> path` blocks, mirroring how Vim records every
    // recently edited file.
    let recent = crate::recent_files::load();

    // File marks: the recent-files list maps to numbered marks `'0`..`'9`.
    out.push_str("# File marks:\n");
    for (i, path) in recent.iter().take(10).enumerate() {
        let mark = (b'0' + i as u8) as char;
        let (line, col) = open_cursor.get(&canon(path)).copied().unwrap_or((1, 0));
        let disp = tildify(path, home);
        let _ = writeln!(out, "'{}  {}  {}  {}", mark, line, col, disp);
        let _ = writeln!(
            out,
            "|4,{},{},{},{},{}",
            '0' as u32 + i as u32,
            line,
            col,
            ts,
            bar_quote(&disp)
        );
    }
    out.push('\n');

    // Jumplist of the focused view, newest first (Vim mark name `'`, code 39).
    out.push_str("# Jumplist (newest first):\n");
    if let Some(view) = editor.tree.try_get(editor.tree.focus) {
        for (doc_id, selection) in view.jumps.iter().rev() {
            if let Some(doc) = editor.document(*doc_id) {
                if let Some(path) = doc.path() {
                    let text = doc.text().slice(..);
                    let pos = selection.primary().cursor(text);
                    let coords = coords_at_pos(text, pos);
                    let disp = tildify(path, home);
                    let _ = writeln!(out, "-'  {}  {}  {}", coords.row + 1, coords.col, disp);
                    let _ = writeln!(
                        out,
                        "|4,39,{},{},{},{}",
                        coords.row + 1,
                        coords.col,
                        ts,
                        bar_quote(&disp)
                    );
                }
            }
        }
    }
    out.push('\n');

    // History of marks within files: one `> path` block per recently edited
    // file, newest first — exactly the list Vim records here, which is also how
    // recent-files consumers (e.g. fzf pickers) harvest the MRU set. Each block
    // carries the `*` last-used timestamp and the `"` last-cursor mark, plus any
    // letter/auto marks when the file is currently open.
    out.push_str("# History of marks within files (newest to oldest):\n");
    for path in &recent {
        let cpath = canon(path);
        let (line, col) = open_cursor.get(&cpath).copied().unwrap_or((1, 0));
        let disp = tildify(path, home);
        // The blank line before each block doubles as the blank after the header.
        let _ = writeln!(out, "\n> {}", disp);
        // The `*` mark is the file's last-used timestamp, not a position.
        let _ = writeln!(out, "\t*\t{}\t0", ts);
        // The `"` mark is the cursor position when last in this file.
        let _ = writeln!(out, "\t\"\t{}\t{}", line, col);
        if let Some(marks) = open_marks.get(&cpath) {
            for (mark, (l, c)) in marks {
                if *mark == '"' {
                    continue;
                }
                let _ = writeln!(out, "\t{}\t{}\t{}", mark, l, c);
            }
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bar_quote_escapes_specials() {
        assert_eq!(bar_quote("q"), "\"q\"");
        assert_eq!(bar_quote("a\"b"), "\"a\\\"b\"");
        assert_eq!(bar_quote("a\\b"), "\"a\\\\b\"");
        assert_eq!(bar_quote("a\nb"), "\"a\\nb\"");
    }

    #[test]
    fn tildify_collapses_home() {
        let home = Path::new("/Users/me");
        assert_eq!(tildify(Path::new("/Users/me/.zshrc"), Some(home)), "~/.zshrc");
        assert_eq!(tildify(Path::new("/Users/me"), Some(home)), "~");
        assert_eq!(tildify(Path::new("/etc/hosts"), Some(home)), "/etc/hosts");
        assert_eq!(tildify(Path::new("/etc/hosts"), None), "/etc/hosts");
    }
}
