//! Unicode character names — the table `C-x 8 RET`, `isearch-char-by-name` and
//! `emoji-describe` look a character up in, in both directions.
//!
//! Emacs reads a character by its name (`insert-char` prompts with completion
//! over `ucs-names`) and reports the name of a character it has no other name
//! for. Both need the Unicode Character Database's name field.
//!
//! Only the **listed** names are stored, in [`NAME_TABLE`] — generated by
//! `scripts/gen_unicode_names.py` from CPython's `unicodedata`, which is the UCD.
//! Unicode derives the rest by rule (UAX #44 §4.8), and deriving them here keeps
//! 110,720 entries out of the repo:
//!
//! * **NR1** — Hangul syllables, composed from the jamo short names.
//! * **NR2** — a fixed prefix plus the codepoint in hex, for the CJK ideograph,
//!   Khitan and Nushu ranges.
//!
//! Lookups are case-insensitive on the name, as Emacs's completion is.

/// The generated table: `HEX;NAME` per line, ascending by codepoint, with two
/// leading `#` comment lines recording the Unicode version it came from.
const NAME_TABLE: &str = include_str!("unicode_names.txt");

/// The ranges whose names Unicode derives as `PREFIX-HEX` (rule NR2), exactly as
/// the UCD lists them — contiguous runs, not a min/max span, so a codepoint in a
/// gap between two runs is correctly nameless rather than given a neighbour's
/// prefix.
const DERIVED_RANGES: &[(u32, u32, &str)] = &[
    (0x3400, 0x4DBF, "CJK UNIFIED IDEOGRAPH"),
    (0x4E00, 0x9FFF, "CJK UNIFIED IDEOGRAPH"),
    (0xF900, 0xFA6D, "CJK COMPATIBILITY IDEOGRAPH"),
    (0xFA70, 0xFAD9, "CJK COMPATIBILITY IDEOGRAPH"),
    (0x18B00, 0x18CD5, "KHITAN SMALL SCRIPT CHARACTER"),
    (0x1B170, 0x1B2FB, "NUSHU CHARACTER"),
    (0x20000, 0x2A6DF, "CJK UNIFIED IDEOGRAPH"),
    (0x2A700, 0x2B739, "CJK UNIFIED IDEOGRAPH"),
    (0x2B740, 0x2B81D, "CJK UNIFIED IDEOGRAPH"),
    (0x2B820, 0x2CEA1, "CJK UNIFIED IDEOGRAPH"),
    (0x2CEB0, 0x2EBE0, "CJK UNIFIED IDEOGRAPH"),
    (0x2EBF0, 0x2EE5D, "CJK UNIFIED IDEOGRAPH"),
    (0x2F800, 0x2FA1D, "CJK COMPATIBILITY IDEOGRAPH"),
    (0x30000, 0x3134A, "CJK UNIFIED IDEOGRAPH"),
    (0x31350, 0x323AF, "CJK UNIFIED IDEOGRAPH"),
];

// The Hangul syllable block and its jamo short names (rule NR1).
const HANGUL_BASE: u32 = 0xAC00;
const HANGUL_COUNT: u32 = 11172;
const JAMO_L: [&str; 19] = [
    "G", "GG", "N", "D", "DD", "R", "M", "B", "BB", "S", "SS", "", "J", "JJ", "C", "K", "T", "P",
    "H",
];
const JAMO_V: [&str; 21] = [
    "A", "AE", "YA", "YAE", "EO", "E", "YEO", "YE", "O", "WA", "WAE", "OE", "YO", "U", "WEO", "WE",
    "WI", "YU", "EU", "YI", "I",
];
const JAMO_T: [&str; 28] = [
    "", "G", "GG", "GS", "N", "NJ", "NH", "D", "L", "LG", "LM", "LB", "LS", "LT", "LP", "LH", "M",
    "B", "BS", "S", "SS", "NG", "J", "C", "K", "T", "P", "H",
];

/// The name Unicode gives `c`, or `None` when it has none (an unassigned
/// codepoint, a control character, a surrogate or a private-use character —
/// Emacs reports no name for those either).
pub fn name(c: char) -> Option<String> {
    let cp = c as u32;
    if let Some(name) = hangul_name(cp) {
        return Some(name);
    }
    if let Some((_, _, prefix)) = DERIVED_RANGES
        .iter()
        .find(|(lo, hi, _)| cp >= *lo && cp <= *hi)
    {
        return Some(format!("{prefix}-{cp:04X}"));
    }
    for line in table_lines() {
        let (hex, name) = line.split_once(';')?;
        let Ok(value) = u32::from_str_radix(hex, 16) else {
            continue;
        };
        // The table ascends, so nothing beyond `cp` can match.
        match value.cmp(&cp) {
            std::cmp::Ordering::Less => continue,
            std::cmp::Ordering::Equal => return Some(name.to_string()),
            std::cmp::Ordering::Greater => return None,
        }
    }
    None
}

/// The character Unicode gives `name`, matched case-insensitively as Emacs's
/// `insert-char` completion is.
pub fn character(name: &str) -> Option<char> {
    let want = name.trim();
    if want.is_empty() {
        return None;
    }
    if let Some(c) = hangul_character(want) {
        return Some(c);
    }
    if let Some(c) = derived_character(want) {
        return Some(c);
    }
    for line in table_lines() {
        let (hex, listed) = line.split_once(';')?;
        if listed.eq_ignore_ascii_case(want) {
            return u32::from_str_radix(hex, 16).ok().and_then(char::from_u32);
        }
    }
    None
}

/// Every `HEX;NAME` line of the table, with the generator's `#` header dropped.
fn table_lines() -> impl Iterator<Item = &'static str> {
    NAME_TABLE
        .lines()
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
}

/// Every listed name, for completion over the table (Emacs's `ucs-names`). The
/// rule-derived ranges are not enumerated: 110,720 CJK and Hangul entries would
/// swamp a completion list, and Emacs's own `ucs-names` leaves them out too.
pub fn listed_names() -> impl Iterator<Item = (char, &'static str)> {
    table_lines().filter_map(|line| {
        let (hex, name) = line.split_once(';')?;
        let c = char::from_u32(u32::from_str_radix(hex, 16).ok()?)?;
        Some((c, name))
    })
}

/// Rule NR1: `HANGUL SYLLABLE <L><V><T>`, composed from the jamo short names.
fn hangul_name(cp: u32) -> Option<String> {
    let index = cp.checked_sub(HANGUL_BASE)?;
    if index >= HANGUL_COUNT {
        return None;
    }
    let l = (index / 588) as usize;
    let v = ((index % 588) / 28) as usize;
    let t = (index % 28) as usize;
    Some(format!(
        "HANGUL SYLLABLE {}{}{}",
        JAMO_L[l], JAMO_V[v], JAMO_T[t]
    ))
}

/// The inverse of [`hangul_name`]: the longest jamo that fits at each position,
/// since the short names are not prefix-free (`G` and `GG`, `S` and `SS`).
fn hangul_character(name: &str) -> Option<char> {
    let rest = name
        .strip_prefix("HANGUL SYLLABLE ")
        .or_else(|| name.strip_prefix("hangul syllable "))?;
    let rest = rest.to_ascii_uppercase();
    let take = |table: &[&str], from: &str| -> Option<(usize, usize)> {
        table
            .iter()
            .enumerate()
            // Longest match first: `GG` must win over `G`.
            .filter(|(_, j)| !j.is_empty() && from.starts_with(*j))
            .max_by_key(|(_, j)| j.len())
            .map(|(i, j)| (i, j.len()))
    };
    let (l, used) = take(&JAMO_L, &rest)?;
    let (v, used_v) = take(&JAMO_V, &rest[used..])?;
    let tail = &rest[used + used_v..];
    let t = if tail.is_empty() {
        0
    } else {
        take(&JAMO_T, tail).filter(|(_, n)| *n == tail.len())?.0
    };
    char::from_u32(HANGUL_BASE + (l as u32 * 21 + v as u32) * 28 + t as u32)
}

/// The inverse of the NR2 rule: `PREFIX-HEX`, accepted only when the codepoint
/// really falls in a range that carries that prefix.
fn derived_character(name: &str) -> Option<char> {
    let (prefix, hex) = name.rsplit_once('-')?;
    let cp = u32::from_str_radix(hex, 16).ok()?;
    DERIVED_RANGES
        .iter()
        .find(|(lo, hi, p)| cp >= *lo && cp <= *hi && p.eq_ignore_ascii_case(prefix))
        .and_then(|_| char::from_u32(cp))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Both directions, over the shapes the table and the two derivation rules
    /// each cover. The expected names are the Unicode Character Database's.
    #[test]
    fn names_round_trip_in_both_directions() {
        // Listed names.
        assert_eq!(name('A').as_deref(), Some("LATIN CAPITAL LETTER A"));
        assert_eq!(character("LATIN CAPITAL LETTER A"), Some('A'));
        assert_eq!(name(' ').as_deref(), Some("SPACE"));
        assert_eq!(name('ä').as_deref(), Some("LATIN SMALL LETTER A WITH DIAERESIS"));
        assert_eq!(character("latin small letter a with diaeresis"), Some('ä'));
        assert_eq!(name('€').as_deref(), Some("EURO SIGN"));

        // NR2: a fixed prefix plus the codepoint in hex.
        assert_eq!(name('\u{4E00}').as_deref(), Some("CJK UNIFIED IDEOGRAPH-4E00"));
        assert_eq!(character("CJK UNIFIED IDEOGRAPH-4E00"), Some('\u{4E00}'));
        assert_eq!(
            name('\u{20000}').as_deref(),
            Some("CJK UNIFIED IDEOGRAPH-20000")
        );

        // NR1: Hangul, including a syllable with no trailing jamo.
        assert_eq!(name('\u{AC00}').as_deref(), Some("HANGUL SYLLABLE GA"));
        assert_eq!(character("HANGUL SYLLABLE GA"), Some('\u{AC00}'));
        assert_eq!(name('\u{AC01}').as_deref(), Some("HANGUL SYLLABLE GAG"));
        assert_eq!(character("HANGUL SYLLABLE GAG"), Some('\u{AC01}'));
        // The jamo short names are not prefix-free: `GG` must beat `G`.
        assert_eq!(name('\u{AE4C}').as_deref(), Some("HANGUL SYLLABLE GGA"));
        assert_eq!(character("HANGUL SYLLABLE GGA"), Some('\u{AE4C}'));
        // The last syllable in the block.
        assert_eq!(name('\u{D7A3}').as_deref(), Some("HANGUL SYLLABLE HIH"));
    }

    /// A character with no name must report none rather than an invented one,
    /// and a name that names nothing must not resolve.
    #[test]
    fn the_nameless_stay_nameless() {
        // A control character: the UCD gives it no name.
        assert_eq!(name('\u{0000}'), None);
        assert_eq!(name('\u{001B}'), None);
        // Just past the Hangul block.
        assert_eq!(name('\u{D7A4}'), None);
        // A gap between two NR2 runs: 0x4DC0..0x4DFF is the hexagram block, which
        // has listed names, and 0xFA6E is a true gap.
        assert!(name('\u{FA6E}').is_none());

        assert_eq!(character(""), None);
        assert_eq!(character("NOT A REAL CHARACTER NAME"), None);
        // The prefix must match the range: this codepoint is not Nushu.
        assert_eq!(character("NUSHU CHARACTER-4E00"), None);
    }
}
