//! Dunnet — the zemacs port of GNU Emacs `dunnet`, the text adventure.
//!
//! The world (105 rooms, the exit matrix, the objects and their placements) is
//! transcribed faithfully from `dunnet.el` — see `dunnet_data.rs`, generated by
//! loading the real game in Emacs and dumping its resolved constants. This
//! overlay implements the explorable core: moving through the map, `look`,
//! `take`/`drop`, `inventory`, `examine`, and `score`. The intricate puzzle and
//! endgame verbs (the bus, the bear, the in-game computer/FTP puzzles, combat)
//! are not ported — special/puzzle exits report that you can't go that way.
//!
//! Type a command and press `RET`; `q`/`Esc` closes the overlay. The game logic
//! is pure and unit-tested (keys parse into a `dunnet` keymap mode by
//! `scripts/gen_port_report.py`).

use tui::buffer::Buffer as Surface;
use zemacs_view::graphics::Rect;

use crate::ui::dunnet_data::{
    DIGGABLES, MAP, OBJECTS, OBJNAMES, OBJ_PTS, PERM_OBJECTS, ROOMS, ROOM_OBJECTS,
};
use crate::{
    compositor::{Callback, Component, Compositor, Context, Event, EventResult},
    ctrl, key,
};

const TREASURE_ROOM: usize = 0;
const START_ROOM: usize = 1;
const SPECIAL: i16 = 255;

/// Direction words → column in the exit matrix
/// `[N,S,E,W,NE,SE,NW,SW,Up,Down,In,Out]`.
fn direction(word: &str) -> Option<usize> {
    Some(match word {
        "north" | "n" => 0,
        "south" | "s" => 1,
        "east" | "e" => 2,
        "west" | "w" => 3,
        "northeast" | "ne" => 4,
        "southeast" | "se" => 5,
        "northwest" | "nw" => 6,
        "southwest" | "sw" => 7,
        "up" | "u" => 8,
        "down" | "d" => 9,
        "in" | "enter" => 10,
        "out" | "exit" | "leave" => 11,
        _ => return None,
    })
}

/// Resolve a player's word to an object number (negative = scenery).
fn object_number(word: &str) -> Option<i16> {
    OBJNAMES.iter().find(|(w, _)| *w == word).map(|(_, n)| *n)
}

/// The pure dunnet world state. No I/O — unit-tested.
#[derive(Clone)]
pub struct Game {
    pub room: usize,
    /// Objects currently in each room (mutable copy of the initial placement).
    pub room_objects: Vec<Vec<i16>>,
    pub inventory: Vec<i16>,
    visited: Vec<bool>,
    /// Rooms already dug (a room yields its buried objects only once).
    dug: std::collections::HashSet<usize>,
}

impl Game {
    pub fn new() -> Self {
        let mut g = Game {
            room: START_ROOM,
            room_objects: ROOM_OBJECTS.iter().map(|r| r.to_vec()).collect(),
            inventory: Vec::new(),
            visited: vec![false; ROOMS.len()],
            dug: std::collections::HashSet::new(),
        };
        g.visited[START_ROOM] = true;
        g
    }

    /// The description of `room`: the long text on the first visit, the short
    /// name afterwards, followed by any objects present.
    pub fn describe(&self, room: usize, force_long: bool) -> Vec<String> {
        let mut out = Vec::new();
        let (long, short) = ROOMS[room];
        if force_long || !self.visited[room] {
            out.extend(long.split('\n').map(str::to_string));
        } else {
            out.push(short.to_string());
        }
        for &obj in &self.room_objects[room] {
            if obj == SPECIAL {
                continue; // puzzle-specific flavor, not ported
            } else if obj >= 0 {
                out.push(OBJECTS[obj as usize].0.to_string());
            } else {
                let desc = PERM_OBJECTS[(-obj) as usize];
                if !desc.is_empty() {
                    out.push(desc.to_string());
                }
            }
        }
        out
    }

    /// Move in `dir` (a matrix column). Returns the resulting output lines.
    pub fn go(&mut self, dir: usize) -> Vec<String> {
        let dest = MAP[self.room][dir];
        if dest < 0 || dest == SPECIAL {
            return vec!["You can't go that way.".into()];
        }
        self.room = dest as usize;
        let lines = self.describe(self.room, false);
        self.visited[self.room] = true;
        lines
    }

    /// Take the named object from the current room.
    pub fn take(&mut self, word: &str) -> String {
        let Some(num) = object_number(word) else {
            return format!("I don't know what a \"{word}\" is.");
        };
        if num < 0 || num == SPECIAL {
            return "You can't take that!".into();
        }
        if let Some(pos) = self.room_objects[self.room].iter().position(|&o| o == num) {
            self.room_objects[self.room].remove(pos);
            self.inventory.push(num);
            "Taken.".into()
        } else {
            "I don't see that here.".into()
        }
    }

    /// Drop the named object into the current room.
    pub fn drop(&mut self, word: &str) -> String {
        let Some(num) = object_number(word) else {
            return format!("I don't know what a \"{word}\" is.");
        };
        if let Some(pos) = self.inventory.iter().position(|&o| o == num) {
            self.inventory.remove(pos);
            self.room_objects[self.room].push(num);
            "Dropped.".into()
        } else {
            "You don't have that.".into()
        }
    }

    /// Emacs `dun-dig`: with the shovel (object 0), dig up whatever is buried in
    /// the current room (from `DIGGABLES`) into the room, once.
    pub fn dig(&mut self) -> String {
        if !self.inventory.contains(&0) {
            return "You have nothing with which to dig.".into();
        }
        let buried = DIGGABLES.get(self.room).copied().unwrap_or(&[]);
        if buried.is_empty() || self.dug.contains(&self.room) {
            return "Digging here reveals nothing.".into();
        }
        self.room_objects[self.room].extend_from_slice(buried);
        // A room only yields its buried objects once (mirrors dun-replace to nil).
        self.dug.insert(self.room);
        "I think you found something.".into()
    }

    pub fn inventory_lines(&self) -> Vec<String> {
        if self.inventory.is_empty() {
            return vec!["You have nothing.".into()];
        }
        let mut out = vec!["You are carrying:".to_string()];
        for &num in &self.inventory {
            out.push(format!("  {}", OBJECTS[num as usize].1));
        }
        out
    }

    /// Treasure-room score: the points of the treasures deposited there.
    pub fn score(&self) -> u32 {
        self.room_objects[TREASURE_ROOM]
            .iter()
            .filter(|&&o| o >= 0)
            .map(|&o| OBJ_PTS[o as usize].max(0) as u32)
            .sum()
    }

    /// Run one typed command line, returning output lines.
    pub fn command(&mut self, line: &str) -> Vec<String> {
        let words: Vec<&str> = line.split_whitespace().collect();
        let Some(&verb) = words.first() else {
            return Vec::new();
        };
        if let Some(dir) = direction(verb) {
            return self.go(dir);
        }
        let arg = words.get(1).copied().unwrap_or("");
        match verb {
            "go" | "walk" | "move" => match direction(arg) {
                Some(dir) => self.go(dir),
                None => vec!["Go where?".into()],
            },
            "look" | "l" => self.describe(self.room, true),
            "take" | "get" | "grab" => vec![self.take(arg)],
            "drop" | "leave" => vec![self.drop(arg)],
            "dig" => vec![self.dig()],
            "inventory" | "inv" | "i" => self.inventory_lines(),
            "examine" | "x" | "inspect" => match object_number(arg) {
                Some(n) if n >= 0 => vec![OBJECTS[n as usize].0.to_string()],
                Some(_) => vec!["You see nothing special.".into()],
                None => vec!["Examine what?".into()],
            },
            "score" => vec![format!("You have {} of a possible 250 points.", self.score())],
            "help" | "?" => vec![
                "Commands: north/south/east/west/ne/se/nw/sw/up/down/in/out,".into(),
                "look, take <obj>, drop <obj>, inventory, examine <obj>, score.".into(),
            ],
            _ => vec![format!("I don't understand \"{line}\".")],
        }
    }
}

impl Default for Game {
    fn default() -> Self {
        Self::new()
    }
}

/// The interactive Dunnet overlay.
pub struct Dunnet {
    game: Game,
    log: Vec<String>,
    input: String,
}

impl Dunnet {
    pub fn new() -> Self {
        let game = Game::new();
        let mut log =
            vec!["Dunnet — a text adventure.  Type `help` for commands, `q` to quit.".to_string()];
        log.extend(game.describe(START_ROOM, true));
        Dunnet {
            game,
            log,
            input: String::new(),
        }
    }

    fn submit(&mut self) {
        let line = self.input.trim().to_string();
        self.input.clear();
        if line.is_empty() {
            return;
        }
        self.log.push(format!("> {line}"));
        self.log.extend(self.game.command(&line));
        // Bound the scrollback.
        let max = 500;
        if self.log.len() > max {
            self.log.drain(0..self.log.len() - max);
        }
    }
}

impl Default for Dunnet {
    fn default() -> Self {
        Self::new()
    }
}

impl Component for Dunnet {
    fn handle_event(&mut self, event: &Event, _cx: &mut Context) -> EventResult {
        let key = match event {
            Event::Key(key) => *key,
            _ => return EventResult::Ignored(None),
        };
        let close: Callback = Box::new(|compositor: &mut Compositor, _cx| {
            compositor.pop();
        });
        match key {
            key!(Esc) | ctrl!('c') => return EventResult::Consumed(Some(close)),
            key!('q') if self.input.is_empty() => return EventResult::Consumed(Some(close)),
            key!(Enter) => {
                if self.input.trim() == "quit" || self.input.trim() == "q" {
                    return EventResult::Consumed(Some(close));
                }
                self.submit();
            }
            key!(Backspace) => {
                self.input.pop();
            }
            key!(c @ ' '..='~') => self.input.push(c),
            _ => {}
        }
        EventResult::Consumed(None)
    }

    fn render(&mut self, area: Rect, surface: &mut Surface, ctx: &mut Context) {
        let theme = &ctx.editor.theme;
        let bg = theme.get("ui.background");
        let text_style = theme.get("ui.text");
        let cmd_style = theme.get("ui.linenr");
        let prompt_style = theme.get("ui.text.focus");

        surface.clear_with(area, bg);
        if area.width < 20 || area.height < 6 {
            return;
        }
        let ox = area.x + 1;
        let width = area.width.saturating_sub(2) as usize;
        let input_y = area.y + area.height - 1;

        let visible = (area.height as usize).saturating_sub(1);
        let start = self.log.len().saturating_sub(visible);
        for (i, line) in self.log[start..].iter().enumerate() {
            let mut s = line.clone();
            if s.chars().count() > width {
                s = s.chars().take(width).collect();
            }
            let style = if line.starts_with('>') { cmd_style } else { text_style };
            surface.set_string(ox, area.y + i as u16, &s, style);
        }
        let mut prompt = format!("> {}", self.input);
        if prompt.chars().count() > width {
            prompt = prompt.chars().skip(prompt.chars().count() - width).collect();
        }
        surface.set_string(ox, input_y, &prompt, prompt_style);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn world_data_is_consistent() {
        assert_eq!(ROOMS.len(), 105);
        assert_eq!(MAP.len(), 105);
        assert_eq!(ROOM_OBJECTS.len(), 105);
        assert_eq!(OBJECTS.len(), 28);
    }

    #[test]
    fn start_room_is_the_dead_end_with_the_shovel() {
        let g = Game::new();
        assert_eq!(g.room, START_ROOM);
        assert_eq!(ROOMS[g.room].1, "Dead end");
        // Object 0 is the shovel, placed at the dead end.
        assert!(g.room_objects[START_ROOM].contains(&0));
    }

    #[test]
    fn moving_east_follows_the_real_exit_matrix() {
        let mut g = Game::new();
        // dungeon-map row 1: east leads to room 2 (E/W Dirt road).
        assert_eq!(MAP[1][2], 2);
        g.go(2); // east
        assert_eq!(g.room, 2);
        assert_eq!(ROOMS[g.room].1, "E/W Dirt road");
    }

    #[test]
    fn blocked_and_special_exits_refuse() {
        let mut g = Game::new();
        // North from the dead end is blocked (-1).
        assert_eq!(MAP[1][0], -1);
        assert_eq!(g.go(0), vec!["You can't go that way.".to_string()]);
        assert_eq!(g.room, 1, "a blocked move does not move you");
    }

    #[test]
    fn take_then_drop_moves_the_object() {
        let mut g = Game::new();
        assert_eq!(g.take("shovel"), "Taken.");
        assert!(g.inventory.contains(&0));
        assert!(!g.room_objects[1].contains(&0));
        assert_eq!(g.drop("shovel"), "Dropped.");
        assert!(g.room_objects[1].contains(&0));
        assert!(g.inventory.is_empty());
    }

    #[test]
    fn scenery_cannot_be_taken() {
        let mut g = Game::new();
        // "trees" or similar scenery resolves to a negative object number.
        let scenery = OBJNAMES.iter().find(|(_, n)| *n < 0);
        if let Some((word, _)) = scenery {
            assert_eq!(g.take(word), "You can't take that!");
        }
    }

    #[test]
    fn digging_needs_the_shovel_and_yields_buried_objects_once() {
        let mut g = Game::new();
        // Room 3 (the fork, soft ground) buries object 2 (the CPU board).
        assert_eq!(DIGGABLES[3], &[2]);
        // Grab the shovel, walk to the fork: dead-end(1) -e-> 2 -e-> fork(3).
        g.take("shovel");
        g.go(2); // to room 2
        g.go(2); // to room 3 (fork)
        assert_eq!(g.room, 3);
        assert!(!g.room_objects[3].contains(&2));
        assert_eq!(g.dig(), "I think you found something.");
        assert!(g.room_objects[3].contains(&2), "the board is dug up");
        // A second dig yields nothing.
        assert_eq!(g.dig(), "Digging here reveals nothing.");
    }

    #[test]
    fn digging_without_a_shovel_fails() {
        let mut g = Game::new();
        g.go(2);
        g.go(2); // fork, but no shovel in hand
        assert_eq!(g.dig(), "You have nothing with which to dig.");
    }

    #[test]
    fn command_parses_directions_and_verbs() {
        let mut g = Game::new();
        // Take the shovel here in the start room, then walk east.
        assert_eq!(g.command("take shovel"), vec!["Taken.".to_string()]);
        assert!(g.command("inventory").iter().any(|l| l.contains("shovel")));
        let out = g.command("east");
        assert!(out.iter().any(|l| l.contains("dirt road")));
    }
}
