//! Dunnet — the zemacs port of GNU Emacs `dunnet`, the text adventure.
//!
//! The world (105 rooms, the exit matrix, the objects and their placements) is
//! transcribed faithfully from `dunnet.el` — see `dunnet_data.rs`, generated by
//! loading the real game in Emacs and dumping its resolved constants. This
//! overlay implements the explorable core: moving through the map, `look`,
//! `take`/`drop`, `inventory`, `examine`, and `score`. The intricate puzzle and
//! endgame verbs (the bus, the bear, the in-game computer/FTP puzzles, combat)
//! are not ported — special/puzzle exits report that you can't go that way.
//!
//! Type a command and press `RET`; `q`/`Esc` closes the overlay. The game logic
//! is pure and unit-tested (keys parse into a `dunnet` keymap mode by
//! `scripts/gen_port_report.py`).

use tui::buffer::Buffer as Surface;
use zemacs_view::graphics::Rect;

use crate::ui::dunnet_data::{
    DIGGABLES, MAP, OBJECTS, OBJNAMES, OBJ_PTS, PERM_OBJECTS, ROOMS, ROOM_OBJECTS,
};
use crate::{
    compositor::{Callback, Component, Compositor, Context, Event, EventResult},
    ctrl, key,
};

const TREASURE_ROOM: usize = 0;
const START_ROOM: usize = 1;
const SPECIAL: i16 = 255;

/// Direction words → column in the exit matrix
/// `[N,S,E,W,NE,SE,NW,SW,Up,Down,In,Out]`.
fn direction(word: &str) -> Option<usize> {
    Some(match word {
        "north" | "n" => 0,
        "south" | "s" => 1,
        "east" | "e" => 2,
        "west" | "w" => 3,
        "northeast" | "ne" => 4,
        "southeast" | "se" => 5,
        "northwest" | "nw" => 6,
        "southwest" | "sw" => 7,
        "up" | "u" => 8,
        "down" | "d" => 9,
        "in" | "enter" => 10,
        "out" | "exit" | "leave" => 11,
        _ => return None,
    })
}

/// Resolve a player's word to an object number (negative = scenery).
fn object_number(word: &str) -> Option<i16> {
    OBJNAMES.iter().find(|(w, _)| *w == word).map(|(_, n)| *n)
}

/// The pure dunnet world state. No I/O — unit-tested.
#[derive(Clone)]
pub struct Game {
    pub room: usize,
    /// Objects currently in each room (mutable copy of the initial placement).
    pub room_objects: Vec<Vec<i16>>,
    pub inventory: Vec<i16>,
    visited: Vec<bool>,
    /// Rooms already dug (a room yields its buried objects only once).
    dug: std::collections::HashSet<usize>,
    // Puzzle state used by the special (255) exits, mirroring the dunnet.el vars.
    key_level: i32,
    sauna_level: i32,
    inbus: bool,
    awaiting_combo: bool,
    pub dead: Option<String>,
}

/// The combination for the gamma-computing-center door (dunnet `dun-combination`).
const COMBINATION: &str = "633";
// Object numbers referenced by the special exits (from the Emacs dump).
const OBJ_KEY: i16 = 4;
const OBJ_BEAR: i16 = -3;
const OBJ_WEIGHT: i16 = 8;
const OBJ_TOWEL: i16 = 13;
const OBJ_BUS: i16 = -18;
const OBJ_LICENSE: i16 = 16;

impl Game {
    pub fn new() -> Self {
        let mut g = Game {
            room: START_ROOM,
            room_objects: ROOM_OBJECTS.iter().map(|r| r.to_vec()).collect(),
            inventory: Vec::new(),
            visited: vec![false; ROOMS.len()],
            dug: std::collections::HashSet::new(),
            key_level: 0,
            sauna_level: 0,
            inbus: false,
            awaiting_combo: false,
            dead: None,
        };
        g.visited[START_ROOM] = true;
        g
    }

    /// The description of `room`: the long text on the first visit, the short
    /// name afterwards, followed by any objects present.
    pub fn describe(&self, room: usize, force_long: bool) -> Vec<String> {
        let mut out = Vec::new();
        let (long, short) = ROOMS[room];
        if force_long || !self.visited[room] {
            out.extend(long.split('\n').map(str::to_string));
        } else {
            out.push(short.to_string());
        }
        for &obj in &self.room_objects[room] {
            if obj == SPECIAL {
                continue; // puzzle-specific flavor, not ported
            } else if obj >= 0 {
                out.push(OBJECTS[obj as usize].0.to_string());
            } else {
                let desc = PERM_OBJECTS[(-obj) as usize];
                if !desc.is_empty() {
                    out.push(desc.to_string());
                }
            }
        }
        out
    }

    /// Move in `dir` (a matrix column). Returns the resulting output lines.
    pub fn go(&mut self, dir: usize) -> Vec<String> {
        let dest = MAP[self.room][dir];
        if dest == SPECIAL {
            return self.special_move(dir);
        }
        if dest < 0 {
            return vec!["You can't go that way.".into()];
        }
        self.enter(dest as usize)
    }

    /// Enter `room`, describing it. (Shared by ordinary and special moves.)
    fn enter(&mut self, room: usize) -> Vec<String> {
        self.room = room;
        let lines = self.describe(room, false);
        self.visited[room] = true;
        lines
    }

    fn here(&self, obj: i16) -> bool {
        self.room_objects[self.room].contains(&obj)
    }

    fn die(&mut self, reason: &str, msg: &str) -> Vec<String> {
        self.dead = Some(reason.to_string());
        let mut out: Vec<String> = msg.split('\n').map(str::to_string).collect();
        out.push(format!("You have died of {reason}.  Press Esc to leave."));
        out
    }

    /// Port of `dun-special-move`: the 255 exits, each gated on a puzzle
    /// condition. Faithful to dunnet.el; the swim-only lakefront exits and the
    /// deep bus-driving traversal are left refusing (documented partial).
    fn special_move(&mut self, dir: usize) -> Vec<String> {
        // Matrix columns: northwest=6, up=8, down=9, in=10, out=11.
        match self.room {
            5 => {
                // building-front: the door needs the brass key.
                if self.inventory.contains(&OBJ_KEY) {
                    self.enter(8)
                } else {
                    vec!["You don't have a key that can open this door.".into()]
                }
            }
            32 => {
                // north-end-of-cave-passage: a 3-digit combination lock.
                self.awaiting_combo = true;
                vec![
                    "You must type a 3 digit combination code to enter this room.".into(),
                    "Enter it as your next command.".into(),
                ]
            }
            7 => {
                // bear-hangout: the bear kills you if it is still here.
                if self.here(OBJ_BEAR) {
                    self.die(
                        "a bear",
                        "The bear is very annoyed that you would be so presumptuous as to try\nand walk right by it.  He tells you so by tearing your head off.",
                    )
                } else {
                    vec!["You can't go that way.".into()]
                }
            }
            89 => {
                // vermont-station: the train takes you to the museum station.
                let mut out = vec![
                    "As you board the train it immediately leaves the station.  It is a very".into(),
                    "bumpy ride, and finally throws you out at another station.".into(),
                ];
                out.extend(self.enter(90));
                out
            }
            8 => {
                // old-building-hallway: needs the key AND a raised key level.
                if self.inventory.contains(&OBJ_KEY) && self.key_level > 0 {
                    self.enter(11)
                } else {
                    vec!["You don't have a key that can open this door.".into()]
                }
            }
            17 if dir == 6 => {
                // maze-button-room northwest: passable only with the weight here.
                if self.here(OBJ_WEIGHT) {
                    self.enter(18)
                } else {
                    vec!["You can't go that way.".into()]
                }
            }
            17 if dir == 8 => {
                // maze-button-room up: blocked while the weight is here.
                if self.here(OBJ_WEIGHT) {
                    vec!["You can't go that way.".into()]
                } else {
                    self.enter(16)
                }
            }
            88 => vec!["The door is locked.".into()],
            23 => {
                // reception-area: leaving is fatal once the sauna is cranked up.
                if self.sauna_level != 3 {
                    self.enter(24)
                } else {
                    self.die(
                        "burning",
                        "As you exit the building, you notice some flames coming out of one of the\nwindows.  Suddenly, the building explodes in a huge ball of fire.",
                    )
                }
            }
            46 => {
                // red-room: a passage opens once the towel is removed.
                if !self.here(OBJ_TOWEL) {
                    self.enter(47)
                } else {
                    vec!["You can't go that way.".into()]
                }
            }
            28 => {
                // cave-entrance: a rockslide seals you into the misty room.
                let mut out = vec![
                    "As you enter the room you hear a rumbling noise.  You look back to see".into(),
                    "huge rocks sliding down from the ceiling, and blocking your way out.".into(),
                ];
                out.extend(self.enter(29));
                out
            }
            25 | 26 => vec!["You'd have to swim, and that isn't ported yet.".into()],
            // The street grid (rooms 58..83): in/out boards/leaves the bus; the
            // cliff and gate specials fire on ordinary moves.
            r if r > 57 && r < 84 => {
                if dir >= 10 {
                    if !self.here(OBJ_BUS) {
                        vec!["You can't go that way.".into()]
                    } else if dir == 10 {
                        if self.inbus {
                            vec!["You are already in the bus!".into()]
                        } else if self.inventory.contains(&OBJ_LICENSE) {
                            self.inbus = true;
                            vec!["You board the bus and get in the driver's seat.".into()]
                        } else {
                            vec!["You are not licensed for this type of vehicle.".into()]
                        }
                    } else if !self.inbus {
                        vec!["You are already off the bus!".into()]
                    } else {
                        self.inbus = false;
                        vec!["You hop off the bus.".into()]
                    }
                } else if r == 80 {
                    // fifth-oaktree-intersection: a cliff.
                    if self.inbus {
                        self.die(
                            "a bus accident",
                            "The bus flies off the cliff, and plunges to the bottom, where it explodes.",
                        )
                    } else {
                        self.die("a cliff", "You fall down the cliff and land on your head.")
                    }
                } else if r == 59 {
                    // main-maple-intersection: the museum gate opens only for the bus.
                    if !self.inbus {
                        vec!["The gate will not open.".into()]
                    } else {
                        if let Some(p) = self.room_objects[59].iter().position(|&o| o == OBJ_BUS) {
                            self.room_objects[59].remove(p);
                        }
                        self.room_objects[83].push(OBJ_BUS);
                        let mut out =
                            vec!["As the bus approaches, the gate opens and you drive through.".into()];
                        out.extend(self.enter(83));
                        out
                    }
                } else {
                    vec!["You can't go that way.".into()]
                }
            }
            _ => vec!["You can't go that way.".into()],
        }
    }

    /// Take the named object from the current room.
    pub fn take(&mut self, word: &str) -> String {
        let Some(num) = object_number(word) else {
            return format!("I don't know what a \"{word}\" is.");
        };
        if num < 0 || num == SPECIAL {
            return "You can't take that!".into();
        }
        if let Some(pos) = self.room_objects[self.room].iter().position(|&o| o == num) {
            self.room_objects[self.room].remove(pos);
            self.inventory.push(num);
            "Taken.".into()
        } else {
            "I don't see that here.".into()
        }
    }

    /// Drop the named object into the current room.
    pub fn drop(&mut self, word: &str) -> String {
        let Some(num) = object_number(word) else {
            return format!("I don't know what a \"{word}\" is.");
        };
        if let Some(pos) = self.inventory.iter().position(|&o| o == num) {
            self.inventory.remove(pos);
            self.room_objects[self.room].push(num);
            "Dropped.".into()
        } else {
            "You don't have that.".into()
        }
    }

    /// Emacs `dun-dig`: with the shovel (object 0), dig up whatever is buried in
    /// the current room (from `DIGGABLES`) into the room, once.
    pub fn dig(&mut self) -> String {
        if !self.inventory.contains(&0) {
            return "You have nothing with which to dig.".into();
        }
        let buried = DIGGABLES.get(self.room).copied().unwrap_or(&[]);
        if buried.is_empty() || self.dug.contains(&self.room) {
            return "Digging here reveals nothing.".into();
        }
        self.room_objects[self.room].extend_from_slice(buried);
        // A room only yields its buried objects once (mirrors dun-replace to nil).
        self.dug.insert(self.room);
        "I think you found something.".into()
    }

    pub fn inventory_lines(&self) -> Vec<String> {
        if self.inventory.is_empty() {
            return vec!["You have nothing.".into()];
        }
        let mut out = vec!["You are carrying:".to_string()];
        for &num in &self.inventory {
            out.push(format!("  {}", OBJECTS[num as usize].1));
        }
        out
    }

    /// Treasure-room score: the points of the treasures deposited there.
    pub fn score(&self) -> u32 {
        self.room_objects[TREASURE_ROOM]
            .iter()
            .filter(|&&o| o >= 0)
            .map(|&o| OBJ_PTS[o as usize].max(0) as u32)
            .sum()
    }

    /// Run one typed command line, returning output lines.
    pub fn command(&mut self, line: &str) -> Vec<String> {
        if self.dead.is_some() {
            return vec!["You are dead.  Press Esc to leave.".into()];
        }
        // A pending combination lock consumes the next line (dun-special-move).
        if self.awaiting_combo {
            self.awaiting_combo = false;
            return if line.trim() == COMBINATION {
                self.enter(57) // gamma-computing-center
            } else {
                vec!["Sorry, that combination is incorrect.".into()]
            };
        }
        let words: Vec<&str> = line.split_whitespace().collect();
        let Some(&verb) = words.first() else {
            return Vec::new();
        };
        if let Some(dir) = direction(verb) {
            return self.go(dir);
        }
        let arg = words.get(1).copied().unwrap_or("");
        match verb {
            "go" | "walk" | "move" => match direction(arg) {
                Some(dir) => self.go(dir),
                None => vec!["Go where?".into()],
            },
            "look" | "l" => self.describe(self.room, true),
            "take" | "get" | "grab" => vec![self.take(arg)],
            "drop" | "leave" => vec![self.drop(arg)],
            "dig" => vec![self.dig()],
            "inventory" | "inv" | "i" => self.inventory_lines(),
            "examine" | "x" | "inspect" => match object_number(arg) {
                Some(n) if n >= 0 => vec![OBJECTS[n as usize].0.to_string()],
                Some(_) => vec!["You see nothing special.".into()],
                None => vec!["Examine what?".into()],
            },
            "score" => vec![format!("You have {} of a possible 250 points.", self.score())],
            "help" | "?" => vec![
                "Commands: north/south/east/west/ne/se/nw/sw/up/down/in/out,".into(),
                "look, take <obj>, drop <obj>, inventory, examine <obj>, score.".into(),
            ],
            _ => vec![format!("I don't understand \"{line}\".")],
        }
    }
}

impl Default for Game {
    fn default() -> Self {
        Self::new()
    }
}

/// The interactive Dunnet overlay.
pub struct Dunnet {
    game: Game,
    log: Vec<String>,
    input: String,
}

impl Dunnet {
    pub fn new() -> Self {
        let game = Game::new();
        let mut log =
            vec!["Dunnet — a text adventure.  Type `help` for commands, `q` to quit.".to_string()];
        log.extend(game.describe(START_ROOM, true));
        Dunnet {
            game,
            log,
            input: String::new(),
        }
    }

    fn submit(&mut self) {
        let line = self.input.trim().to_string();
        self.input.clear();
        if line.is_empty() {
            return;
        }
        self.log.push(format!("> {line}"));
        self.log.extend(self.game.command(&line));
        // Bound the scrollback.
        let max = 500;
        if self.log.len() > max {
            self.log.drain(0..self.log.len() - max);
        }
    }
}

impl Default for Dunnet {
    fn default() -> Self {
        Self::new()
    }
}

impl Component for Dunnet {
    fn handle_event(&mut self, event: &Event, _cx: &mut Context) -> EventResult {
        let key = match event {
            Event::Key(key) => *key,
            _ => return EventResult::Ignored(None),
        };
        let close: Callback = Box::new(|compositor: &mut Compositor, _cx| {
            compositor.pop();
        });
        match key {
            key!(Esc) | ctrl!('c') => return EventResult::Consumed(Some(close)),
            key!('q') if self.input.is_empty() => return EventResult::Consumed(Some(close)),
            key!(Enter) => {
                if self.input.trim() == "quit" || self.input.trim() == "q" {
                    return EventResult::Consumed(Some(close));
                }
                self.submit();
            }
            key!(Backspace) => {
                self.input.pop();
            }
            key!(c @ ' '..='~') => self.input.push(c),
            _ => {}
        }
        EventResult::Consumed(None)
    }

    fn render(&mut self, area: Rect, surface: &mut Surface, ctx: &mut Context) {
        let theme = &ctx.editor.theme;
        let bg = theme.get("ui.background");
        let text_style = theme.get("ui.text");
        let cmd_style = theme.get("ui.linenr");
        let prompt_style = theme.get("ui.text.focus");

        surface.clear_with(area, bg);
        if area.width < 20 || area.height < 6 {
            return;
        }
        let ox = area.x + 1;
        let width = area.width.saturating_sub(2) as usize;
        let input_y = area.y + area.height - 1;

        let visible = (area.height as usize).saturating_sub(1);
        let start = self.log.len().saturating_sub(visible);
        for (i, line) in self.log[start..].iter().enumerate() {
            let mut s = line.clone();
            if s.chars().count() > width {
                s = s.chars().take(width).collect();
            }
            let style = if line.starts_with('>') { cmd_style } else { text_style };
            surface.set_string(ox, area.y + i as u16, &s, style);
        }
        let mut prompt = format!("> {}", self.input);
        if prompt.chars().count() > width {
            prompt = prompt.chars().skip(prompt.chars().count() - width).collect();
        }
        surface.set_string(ox, input_y, &prompt, prompt_style);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn world_data_is_consistent() {
        assert_eq!(ROOMS.len(), 105);
        assert_eq!(MAP.len(), 105);
        assert_eq!(ROOM_OBJECTS.len(), 105);
        assert_eq!(OBJECTS.len(), 28);
    }

    #[test]
    fn start_room_is_the_dead_end_with_the_shovel() {
        let g = Game::new();
        assert_eq!(g.room, START_ROOM);
        assert_eq!(ROOMS[g.room].1, "Dead end");
        // Object 0 is the shovel, placed at the dead end.
        assert!(g.room_objects[START_ROOM].contains(&0));
    }

    #[test]
    fn moving_east_follows_the_real_exit_matrix() {
        let mut g = Game::new();
        // dungeon-map row 1: east leads to room 2 (E/W Dirt road).
        assert_eq!(MAP[1][2], 2);
        g.go(2); // east
        assert_eq!(g.room, 2);
        assert_eq!(ROOMS[g.room].1, "E/W Dirt road");
    }

    #[test]
    fn blocked_and_special_exits_refuse() {
        let mut g = Game::new();
        // North from the dead end is blocked (-1).
        assert_eq!(MAP[1][0], -1);
        assert_eq!(g.go(0), vec!["You can't go that way.".to_string()]);
        assert_eq!(g.room, 1, "a blocked move does not move you");
    }

    #[test]
    fn take_then_drop_moves_the_object() {
        let mut g = Game::new();
        assert_eq!(g.take("shovel"), "Taken.");
        assert!(g.inventory.contains(&0));
        assert!(!g.room_objects[1].contains(&0));
        assert_eq!(g.drop("shovel"), "Dropped.");
        assert!(g.room_objects[1].contains(&0));
        assert!(g.inventory.is_empty());
    }

    #[test]
    fn scenery_cannot_be_taken() {
        let mut g = Game::new();
        // "trees" or similar scenery resolves to a negative object number.
        let scenery = OBJNAMES.iter().find(|(_, n)| *n < 0);
        if let Some((word, _)) = scenery {
            assert_eq!(g.take(word), "You can't take that!");
        }
    }

    #[test]
    fn digging_needs_the_shovel_and_yields_buried_objects_once() {
        let mut g = Game::new();
        // Room 3 (the fork, soft ground) buries object 2 (the CPU board).
        assert_eq!(DIGGABLES[3], &[2]);
        // Grab the shovel, walk to the fork: dead-end(1) -e-> 2 -e-> fork(3).
        g.take("shovel");
        g.go(2); // to room 2
        g.go(2); // to room 3 (fork)
        assert_eq!(g.room, 3);
        assert!(!g.room_objects[3].contains(&2));
        assert_eq!(g.dig(), "I think you found something.");
        assert!(g.room_objects[3].contains(&2), "the board is dug up");
        // A second dig yields nothing.
        assert_eq!(g.dig(), "Digging here reveals nothing.");
    }

    #[test]
    fn digging_without_a_shovel_fails() {
        let mut g = Game::new();
        g.go(2);
        g.go(2); // fork, but no shovel in hand
        assert_eq!(g.dig(), "You have nothing with which to dig.");
    }

    #[test]
    fn building_front_needs_the_key() {
        // Room 5 (building-front) has a 255 exit into room 8, gated on the key.
        let mut g = Game::new();
        assert!(MAP[5].contains(&255));
        g.room = 5;
        let dir = MAP[5].iter().position(|&d| d == 255).unwrap();
        // Without the key it refuses; with the key you enter room 8.
        assert_eq!(g.go(dir), vec!["You don't have a key that can open this door.".to_string()]);
        g.inventory.push(OBJ_KEY);
        g.go(dir);
        assert_eq!(g.room, 8);
    }

    #[test]
    fn combination_lock_gates_the_gamma_room() {
        let mut g = Game::new();
        g.room = 32;
        let dir = MAP[32].iter().position(|&d| d == 255).unwrap();
        g.go(dir);
        assert!(g.awaiting_combo);
        assert_eq!(g.command("000"), vec!["Sorry, that combination is incorrect.".to_string()]);
        // Correct combo enters the gamma computing center (room 57).
        g.room = 32;
        g.go(dir);
        g.command("633");
        assert_eq!(g.room, 57);
    }

    #[test]
    fn the_bear_is_fatal() {
        let mut g = Game::new();
        g.room = 7; // bear-hangout, the bear (-3) starts here
        assert!(g.here(OBJ_BEAR));
        let dir = MAP[7].iter().position(|&d| d == 255).unwrap();
        g.go(dir);
        assert!(g.dead.is_some(), "walking past the bear kills you");
    }

    #[test]
    fn command_parses_directions_and_verbs() {
        let mut g = Game::new();
        // Take the shovel here in the start room, then walk east.
        assert_eq!(g.command("take shovel"), vec!["Taken.".to_string()]);
        assert!(g.command("inventory").iter().any(|l| l.contains("shovel")));
        let out = g.command("east");
        assert!(out.iter().any(|l| l.contains("dirt road")));
    }
}
