//! Dunnet — the zemacs port of GNU Emacs `dunnet`, the text adventure.
//!
//! The world (105 rooms, the exit matrix, the objects and their placements) is
//! transcribed faithfully from `dunnet.el` — see `dunnet_data.rs`, generated by
//! loading the real game in Emacs and dumping its resolved constants. This
//! overlay implements the explorable core: moving through the map, `look`,
//! `take`/`drop`, `inventory`, `examine`, and `score`. The intricate puzzle and
//! endgame verbs (the bus, the bear, the in-game computer/FTP puzzles, combat)
//! are not ported — special/puzzle exits report that you can't go that way.
//!
//! Type a command and press `RET`; `q`/`Esc` closes the overlay. The game logic
//! is pure and unit-tested (keys parse into a `dunnet` keymap mode by
//! `scripts/gen_port_report.py`).

use tui::buffer::Buffer as Surface;
use zemacs_view::graphics::Rect;

use crate::ui::dunnet_data::{
    DIGGABLES, MAP, OBJECTS, OBJNAMES, OBJ_LBS, OBJ_PTS, PERM_OBJECTS, ROOMS, ROOM_OBJECTS,
};
use crate::{
    compositor::{Callback, Component, Compositor, Context, Event, EventResult},
    ctrl, key,
};

const TREASURE_ROOM: usize = 0;
const START_ROOM: usize = 1;
const SPECIAL: i16 = 255;

/// Direction words → column in the exit matrix
/// `[N,S,E,W,NE,SE,NW,SW,Up,Down,In,Out]`.
fn direction(word: &str) -> Option<usize> {
    Some(match word {
        "north" | "n" => 0,
        "south" | "s" => 1,
        "east" | "e" => 2,
        "west" | "w" => 3,
        "northeast" | "ne" => 4,
        "southeast" | "se" => 5,
        "northwest" | "nw" => 6,
        "southwest" | "sw" => 7,
        "up" | "u" => 8,
        "down" | "d" => 9,
        "in" | "enter" => 10,
        "out" | "exit" | "leave" => 11,
        _ => return None,
    })
}

/// Resolve a player's word to an object number (negative = scenery).
fn object_number(word: &str) -> Option<i16> {
    OBJNAMES.iter().find(|(w, _)| *w == word).map(|(_, n)| *n)
}

/// The pure dunnet world state. No I/O — unit-tested.
#[derive(Clone)]
pub struct Game {
    pub room: usize,
    /// Objects currently in each room (mutable copy of the initial placement).
    pub room_objects: Vec<Vec<i16>>,
    pub inventory: Vec<i16>,
    visited: Vec<bool>,
    /// Rooms already dug (a room yields its buried objects only once).
    dug: std::collections::HashSet<usize>,
    // Puzzle state used by the special (255) exits, mirroring the dunnet.el vars.
    key_level: i32,
    sauna_level: i32,
    inbus: bool,
    awaiting_combo: bool,
    pub dead: Option<String>,
    computer: bool,
    floppy: bool,
    nomail: bool,
    black: bool,
    jar: Vec<i16>,
}

/// The combination for the gamma-computing-center door (dunnet `dun-combination`).
const COMBINATION: &str = "633";
// Object numbers referenced by the special exits (from the Emacs dump).
const OBJ_KEY: i16 = 4;
const OBJ_BEAR: i16 = -3;
const OBJ_WEIGHT: i16 = 8;
const OBJ_TOWEL: i16 = 13;
const OBJ_BUS: i16 = -18;
const OBJ_LICENSE: i16 = 16;
const OBJ_COMPUTER: i16 = -5;
const OBJ_CPU: i16 = 2;
const OBJ_BUTTON: i16 = -8;
const OBJ_JAR: i16 = 19;
const OBJ_CHUTE: i16 = -9;
const OBJ_BOX: i16 = -15;
const OBJ_DROP: i16 = -17;
const OBJ_DISPOSAL: i16 = -26;
const OBJ_PC: i16 = -29;
const OBJ_FLOPPY: i16 = 27;
const COMPUTER_ROOM: usize = 10;
const RED_ROOM: usize = 46;
const MAX_WEIGHT: i16 = 11;
/// Objects that fit in the glass jar (dunnet.el `dun-put-objs`).
const JAR_FITS: &[i16] = &[5, 7, 10, 16, 17, 18, 21, 22];

impl Game {
    pub fn new() -> Self {
        let mut g = Game {
            room: START_ROOM,
            room_objects: ROOM_OBJECTS.iter().map(|r| r.to_vec()).collect(),
            inventory: Vec::new(),
            visited: vec![false; ROOMS.len()],
            dug: std::collections::HashSet::new(),
            key_level: 0,
            sauna_level: 0,
            inbus: false,
            awaiting_combo: false,
            dead: None,
            computer: false,
            floppy: false,
            nomail: false,
            black: false,
            jar: Vec::new(),
        };
        g.visited[START_ROOM] = true;
        g
    }

    /// The description of `room`: the long text on the first visit, the short
    /// name afterwards, followed by any objects present.
    pub fn describe(&self, room: usize, force_long: bool) -> Vec<String> {
        let mut out = Vec::new();
        let (long, short) = ROOMS[room];
        if force_long || !self.visited[room] {
            out.extend(long.split('\n').map(str::to_string));
        } else {
            out.push(short.to_string());
        }
        for &obj in &self.room_objects[room] {
            if obj == SPECIAL {
                continue; // puzzle-specific flavor, not ported
            } else if obj >= 0 {
                out.push(OBJECTS[obj as usize].0.to_string());
            } else {
                let desc = PERM_OBJECTS[(-obj) as usize];
                if !desc.is_empty() {
                    out.push(desc.to_string());
                }
            }
        }
        out
    }

    /// Move in `dir` (a matrix column). Returns the resulting output lines.
    pub fn go(&mut self, dir: usize) -> Vec<String> {
        let dest = MAP[self.room][dir];
        if dest == SPECIAL {
            return self.special_move(dir);
        }
        if dest < 0 {
            return vec!["You can't go that way.".into()];
        }
        self.enter(dest as usize)
    }

    /// Enter `room`, describing it. (Shared by ordinary and special moves.)
    fn enter(&mut self, room: usize) -> Vec<String> {
        self.room = room;
        let lines = self.describe(room, false);
        self.visited[room] = true;
        lines
    }

    fn here(&self, obj: i16) -> bool {
        self.room_objects[self.room].contains(&obj)
    }

    fn die(&mut self, reason: &str, msg: &str) -> Vec<String> {
        self.dead = Some(reason.to_string());
        let mut out: Vec<String> = msg.split('\n').map(str::to_string).collect();
        out.push(format!("You have died of {reason}.  Press Esc to leave."));
        out
    }

    /// Port of `dun-special-move`: the 255 exits, each gated on a puzzle
    /// condition. Faithful to dunnet.el; the swim-only lakefront exits and the
    /// deep bus-driving traversal are left refusing (documented partial).
    fn special_move(&mut self, dir: usize) -> Vec<String> {
        // Matrix columns: northwest=6, up=8, down=9, in=10, out=11.
        match self.room {
            5 => {
                // building-front: the door needs the brass key.
                if self.inventory.contains(&OBJ_KEY) {
                    self.enter(8)
                } else {
                    vec!["You don't have a key that can open this door.".into()]
                }
            }
            32 => {
                // north-end-of-cave-passage: a 3-digit combination lock.
                self.awaiting_combo = true;
                vec![
                    "You must type a 3 digit combination code to enter this room.".into(),
                    "Enter it as your next command.".into(),
                ]
            }
            7 => {
                // bear-hangout: the bear kills you if it is still here.
                if self.here(OBJ_BEAR) {
                    self.die(
                        "a bear",
                        "The bear is very annoyed that you would be so presumptuous as to try\nand walk right by it.  He tells you so by tearing your head off.",
                    )
                } else {
                    vec!["You can't go that way.".into()]
                }
            }
            89 => {
                // vermont-station: the train takes you to the museum station.
                let mut out = vec![
                    "As you board the train it immediately leaves the station.  It is a very"
                        .into(),
                    "bumpy ride, and finally throws you out at another station.".into(),
                ];
                out.extend(self.enter(90));
                out
            }
            8 => {
                // old-building-hallway: needs the key AND a raised key level.
                if self.inventory.contains(&OBJ_KEY) && self.key_level > 0 {
                    self.enter(11)
                } else {
                    vec!["You don't have a key that can open this door.".into()]
                }
            }
            17 if dir == 6 => {
                // maze-button-room northwest: passable only with the weight here.
                if self.here(OBJ_WEIGHT) {
                    self.enter(18)
                } else {
                    vec!["You can't go that way.".into()]
                }
            }
            17 if dir == 8 => {
                // maze-button-room up: blocked while the weight is here.
                if self.here(OBJ_WEIGHT) {
                    vec!["You can't go that way.".into()]
                } else {
                    self.enter(16)
                }
            }
            88 => vec!["The door is locked.".into()],
            23 => {
                // reception-area: leaving is fatal once the sauna is cranked up.
                if self.sauna_level != 3 {
                    self.enter(24)
                } else {
                    self.die(
                        "burning",
                        "As you exit the building, you notice some flames coming out of one of the\nwindows.  Suddenly, the building explodes in a huge ball of fire.",
                    )
                }
            }
            46 => {
                // red-room: a passage opens once the towel is removed.
                if !self.here(OBJ_TOWEL) {
                    self.enter(47)
                } else {
                    vec!["You can't go that way.".into()]
                }
            }
            28 => {
                // cave-entrance: a rockslide seals you into the misty room.
                let mut out = vec![
                    "As you enter the room you hear a rumbling noise.  You look back to see".into(),
                    "huge rocks sliding down from the ceiling, and blocking your way out.".into(),
                ];
                out.extend(self.enter(29));
                out
            }
            25 | 26 => self.swim(),
            // The street grid (rooms 58..83): in/out boards/leaves the bus; the
            // cliff and gate specials fire on ordinary moves.
            r if r > 57 && r < 84 => {
                if dir >= 10 {
                    if !self.here(OBJ_BUS) {
                        vec!["You can't go that way.".into()]
                    } else if dir == 10 {
                        if self.inbus {
                            vec!["You are already in the bus!".into()]
                        } else if self.inventory.contains(&OBJ_LICENSE) {
                            self.inbus = true;
                            self.nomail = true;
                            vec!["You board the bus and get in the driver's seat.".into()]
                        } else {
                            vec!["You are not licensed for this type of vehicle.".into()]
                        }
                    } else if !self.inbus {
                        vec!["You are already off the bus!".into()]
                    } else {
                        self.inbus = false;
                        vec!["You hop off the bus.".into()]
                    }
                } else if r == 80 {
                    // fifth-oaktree-intersection: a cliff.
                    if self.inbus {
                        self.die(
                            "a bus accident",
                            "The bus flies off the cliff, and plunges to the bottom, where it explodes.",
                        )
                    } else {
                        self.die("a cliff", "You fall down the cliff and land on your head.")
                    }
                } else if r == 59 {
                    // main-maple-intersection: the museum gate opens only for the bus.
                    if !self.inbus {
                        vec!["The gate will not open.".into()]
                    } else {
                        if let Some(p) = self.room_objects[59].iter().position(|&o| o == OBJ_BUS) {
                            self.room_objects[59].remove(p);
                        }
                        self.room_objects[83].push(OBJ_BUS);
                        let mut out = vec![
                            "As the bus approaches, the gate opens and you drive through.".into(),
                        ];
                        out.extend(self.enter(83));
                        out
                    }
                } else {
                    vec!["You can't go that way.".into()]
                }
            }
            _ => vec!["You can't go that way.".into()],
        }
    }

    /// Total weight carried (inventory + jar contents), per `dun-inven-weight`.
    fn inven_weight(&self) -> i16 {
        self.inventory
            .iter()
            .chain(self.jar.iter())
            .filter(|&&o| o >= 0)
            .map(|&o| OBJ_LBS[o as usize])
            .sum()
    }

    /// Take the named object from the current room, enforcing the 11-lb carry
    /// limit (`dun-take-object`).
    pub fn take(&mut self, word: &str) -> String {
        let Some(num) = object_number(word) else {
            return format!("I don't know what a \"{word}\" is.");
        };
        if num < 0 || num == SPECIAL {
            return "You cannot take that.".into();
        }
        if !self.room_objects[self.room].contains(&num) {
            return "I do not see that here.".into();
        }
        if !self.inventory.is_empty() && self.inven_weight() + OBJ_LBS[num as usize] > MAX_WEIGHT {
            return "Your load would be too heavy.".into();
        }
        let pos = self.room_objects[self.room]
            .iter()
            .position(|&o| o == num)
            .unwrap();
        self.room_objects[self.room].remove(pos);
        self.inventory.push(num);
        if num == OBJ_TOWEL && self.room == RED_ROOM {
            "Taken.  Taking the towel reveals a hole in the floor.".into()
        } else {
            "Taken.".into()
        }
    }

    /// Port of `dun-put`/`dun-put-objs`: put object `word1` in/on `word2`.
    pub fn put(&mut self, word1: &str, word2: &str) -> String {
        let Some(o1) = object_number(word1) else {
            return "I don't know what that object is.".into();
        };
        if !self.inventory.contains(&o1) {
            return "You don't have that.".into();
        }
        let Some(mut o2) = object_number(word2) else {
            return "I don't know what that indirect object is.".into();
        };
        // A mail-drop / disposal both route to the treasure chute.
        if (o2 == OBJ_DROP && !self.nomail) || o2 == OBJ_DISPOSAL {
            o2 = OBJ_CHUTE;
        }
        // The indirect object must be present (in the room or carried).
        if !self.here(o2) && !self.inventory.contains(&o2) && o2 != OBJ_CHUTE {
            return "That indirect object is not here.".into();
        }
        self.put_objs(o1, o2)
    }

    fn remove_from_inventory(&mut self, obj: i16) {
        if let Some(p) = self.inventory.iter().position(|&o| o == obj) {
            self.inventory.remove(p);
        }
    }

    fn put_objs(&mut self, o1: i16, o2: i16) -> String {
        if o1 == OBJ_CPU && o2 == OBJ_COMPUTER {
            self.remove_from_inventory(OBJ_CPU);
            self.computer = true;
            return "As you put the CPU board in the computer, it immediately springs to life.\nThe lights start flashing, and the fans seem to startup.".into();
        }
        if o1 == OBJ_WEIGHT && o2 == OBJ_BUTTON {
            return self.drop("weight");
        }
        if o2 == OBJ_JAR {
            if !JAR_FITS.contains(&o1) {
                return "That will not fit in the jar.".into();
            }
            self.remove_from_inventory(o1);
            self.jar.push(o1);
            return "Done.".into();
        }
        if o2 == OBJ_CHUTE {
            self.remove_from_inventory(o1);
            // Slides into the treasure room (scoring).
            self.room_objects[TREASURE_ROOM].push(o1);
            return "You hear it slide down the chute and off into the distance.".into();
        }
        if o2 == OBJ_BOX {
            if o1 != OBJ_KEY {
                return "You can't put that in the key box!".into();
            }
            self.remove_from_inventory(OBJ_KEY);
            self.room_objects[COMPUTER_ROOM].push(OBJ_KEY);
            if let Some(p) = self.room_objects[self.room]
                .iter()
                .position(|&o| o == OBJ_BOX)
            {
                self.room_objects[self.room].remove(p);
            }
            self.key_level += 1;
            return "As you drop the key, the box begins to shake.  Finally it explodes\nwith a bang.  The key seems to have vanished!".into();
        }
        if o1 == OBJ_FLOPPY && o2 == OBJ_PC {
            self.remove_from_inventory(OBJ_FLOPPY);
            self.floppy = true;
            return "Done.".into();
        }
        "You can't do that.".into()
    }

    /// Drop the named object into the current room.
    pub fn drop(&mut self, word: &str) -> String {
        let Some(num) = object_number(word) else {
            return format!("I don't know what a \"{word}\" is.");
        };
        if let Some(pos) = self.inventory.iter().position(|&o| o == num) {
            self.inventory.remove(pos);
            self.room_objects[self.room].push(num);
            "Dropped.".into()
        } else {
            "You don't have that.".into()
        }
    }

    /// Emacs `dun-dig`: with the shovel (object 0), dig up whatever is buried in
    /// the current room (from `DIGGABLES`) into the room, once.
    pub fn dig(&mut self) -> String {
        if !self.inventory.contains(&0) {
            return "You have nothing with which to dig.".into();
        }
        let buried = DIGGABLES.get(self.room).copied().unwrap_or(&[]);
        if buried.is_empty() || self.dug.contains(&self.room) {
            return "Digging here reveals nothing.".into();
        }
        self.room_objects[self.room].extend_from_slice(buried);
        // A room only yields its buried objects once (mirrors dun-replace to nil).
        self.dug.insert(self.room);
        "I think you found something.".into()
    }

    pub fn inventory_lines(&self) -> Vec<String> {
        if self.inventory.is_empty() {
            return vec!["You have nothing.".into()];
        }
        let mut out = vec!["You are carrying:".to_string()];
        for &num in &self.inventory {
            out.push(format!("  {}", OBJECTS[num as usize].1));
        }
        out
    }

    /// Regular score (`dun-reg-score`): points of the treasures deposited in the
    /// treasure room, out of a possible 90.
    pub fn score(&self) -> u32 {
        self.room_objects[TREASURE_ROOM]
            .iter()
            .filter(|&&o| o >= 0)
            .map(|&o| OBJ_PTS[o as usize].max(0) as u32)
            .sum()
    }

    /// Port of `dun-swim`: at the lakefront, drown without a life preserver
    /// (object 9), otherwise cross to the other shore.
    pub fn swim(&mut self) -> Vec<String> {
        if self.room != 25 && self.room != 26 {
            return vec!["I see no water!".into()];
        }
        if !self.inventory.contains(&9) {
            return self.die(
                "drowning",
                "You dive in the water, and at first notice it is quite cold.  You then\nstart to get used to it as you realize that you never really learned how\nto swim.",
            );
        }
        if self.room == 25 {
            self.room = 26;
        } else {
            self.room = 25;
        }
        self.describe(self.room, false)
    }

    /// Port of `dun-break`: needs the axe (object 14). Breaking a held object
    /// kills you; a scenery object shatters the axe; a regular object here is
    /// destroyed. The ethernet cable would start the (unported) endgame.
    pub fn break_obj(&mut self, word: &str) -> Vec<String> {
        if !self.inventory.contains(&14) {
            return vec!["You have nothing you can use to break things.".into()];
        }
        let Some(num) = object_number(word) else {
            return vec!["I don't know what that is.".into()];
        };
        if self.inventory.contains(&num) {
            return self.die(
                "an axe",
                "You take the object in your hands and swing the axe.  Unfortunately, you miss\nthe object and slice off your hand.  You bleed to death.",
            );
        }
        if !self.here(num) {
            return vec!["I don't see that here.".into()];
        }
        if num == -16 {
            // obj-cable: normally cuts the connection and starts the endgame.
            return vec![
                "As you break the ethernet cable, everything starts to blur.  You collapse".into(),
                "for a moment, then straighten yourself up.".into(),
                "(The dunnet endgame computer puzzle is not yet ported.)".into(),
            ];
        }
        if num < 0 {
            self.remove_from_inventory(14);
            vec!["Your axe shatters into a million pieces.".into()]
        } else {
            if let Some(p) = self.room_objects[self.room].iter().position(|&o| o == num) {
                self.room_objects[self.room].remove(p);
            }
            vec!["Your axe breaks it into a million pieces.".into()]
        }
    }

    /// Port of `dun-drive`.
    pub fn drive(&self) -> String {
        if !self.inbus {
            "You cannot drive when you aren't in a vehicle.".into()
        } else {
            "To drive while you are in the bus, just give a direction.".into()
        }
    }

    /// Port of `dun-eat`: only the food (object 3) is edible; anything else
    /// chokes you to death.
    pub fn eat(&mut self, word: &str) -> String {
        let Some(num) = object_number(word) else {
            return "I don't know what that is.".into();
        };
        if !self.inventory.contains(&num) {
            return "You don't have that.".into();
        }
        if num != 3 {
            self.dead = Some("choking".into());
            let name = OBJECTS[num as usize].1.to_lowercase();
            return format!("You forcefully shove {name} down your throat, and start choking.");
        }
        self.remove_from_inventory(3);
        "That tasted horrible.".into()
    }

    /// Port of `dun-press`: press the button or the (light) switch.
    pub fn press(&mut self, word: &str) -> String {
        let Some(num) = object_number(word) else {
            return "I don't see that here.".into();
        };
        if !self.here(num) {
            return "I don't see that here.".into();
        }
        if num == OBJ_BUTTON {
            "As you press the button, you notice a passageway open up, but\nas you release it, the passageway closes.".into()
        } else if num == -24 {
            // obj-switch: toggles the black-light.
            self.black = !self.black;
            if self.black {
                "The button is now in the on position.".into()
            } else {
                "The button is now in the off position.".into()
            }
        } else {
            "You can't press that.".into()
        }
    }

    /// Run one typed command line, returning output lines.
    pub fn command(&mut self, line: &str) -> Vec<String> {
        if self.dead.is_some() {
            return vec!["You are dead.  Press Esc to leave.".into()];
        }
        // A pending combination lock consumes the next line (dun-special-move).
        if self.awaiting_combo {
            self.awaiting_combo = false;
            return if line.trim() == COMBINATION {
                self.enter(57) // gamma-computing-center
            } else {
                vec!["Sorry, that combination is incorrect.".into()]
            };
        }
        let words: Vec<&str> = line.split_whitespace().collect();
        let Some(&verb) = words.first() else {
            return Vec::new();
        };
        if let Some(dir) = direction(verb) {
            return self.go(dir);
        }
        let arg = words.get(1).copied().unwrap_or("");
        match verb {
            "go" | "walk" | "move" => match direction(arg) {
                Some(dir) => self.go(dir),
                None => vec!["Go where?".into()],
            },
            "look" | "l" => self.describe(self.room, true),
            "take" | "get" | "grab" => vec![self.take(arg)],
            "drop" | "leave" => vec![self.drop(arg)],
            "dig" => vec![self.dig()],
            "put" | "place" | "insert" => {
                let o1 = arg;
                let o2 = words[2..]
                    .iter()
                    .rev()
                    .find(|w| !matches!(**w, "in" | "on" | "into" | "inside" | "the"))
                    .copied()
                    .unwrap_or("");
                if o1.is_empty() {
                    vec!["You must supply an object".into()]
                } else if o2.is_empty() {
                    vec!["You must supply an indirect object.".into()]
                } else {
                    vec![self.put(o1, o2)]
                }
            }
            "inventory" | "inv" | "i" => self.inventory_lines(),
            "examine" | "x" | "inspect" => match object_number(arg) {
                Some(n) if n >= 0 => vec![OBJECTS[n as usize].0.to_string()],
                Some(_) => vec!["You see nothing special.".into()],
                None => vec!["Examine what?".into()],
            },
            "eat" => vec![self.eat(arg)],
            "press" | "push" => vec![self.press(arg)],
            "break" | "cut" => self.break_obj(arg),
            "drive" => vec![self.drive()],
            "swim" => self.swim(),
            "score" => vec![format!(
                "You have scored {} out of a possible 90 points.",
                self.score()
            )],
            "help" | "?" => vec![
                "Commands: north/south/east/west/ne/se/nw/sw/up/down/in/out,".into(),
                "look, take <obj>, drop <obj>, inventory, examine <obj>, score.".into(),
            ],
            _ => vec![format!("I don't understand \"{line}\".")],
        }
    }
}

impl Default for Game {
    fn default() -> Self {
        Self::new()
    }
}

/// The interactive Dunnet overlay.
pub struct Dunnet {
    game: Game,
    log: Vec<String>,
    input: String,
}

impl Dunnet {
    pub fn new() -> Self {
        let game = Game::new();
        let mut log =
            vec!["Dunnet — a text adventure.  Type `help` for commands, `q` to quit.".to_string()];
        log.extend(game.describe(START_ROOM, true));
        Dunnet {
            game,
            log,
            input: String::new(),
        }
    }

    fn submit(&mut self) {
        let line = self.input.trim().to_string();
        self.input.clear();
        if line.is_empty() {
            return;
        }
        self.log.push(format!("> {line}"));
        self.log.extend(self.game.command(&line));
        // Bound the scrollback.
        let max = 500;
        if self.log.len() > max {
            self.log.drain(0..self.log.len() - max);
        }
    }
}

impl Default for Dunnet {
    fn default() -> Self {
        Self::new()
    }
}

impl Component for Dunnet {
    fn handle_event(&mut self, event: &Event, _cx: &mut Context) -> EventResult {
        let key = match event {
            Event::Key(key) => *key,
            _ => return EventResult::Ignored(None),
        };
        let close: Callback = Box::new(|compositor: &mut Compositor, _cx| {
            compositor.pop();
        });
        match key {
            key!(Esc) | ctrl!('c') => return EventResult::Consumed(Some(close)),
            key!('q') if self.input.is_empty() => return EventResult::Consumed(Some(close)),
            key!(Enter) => {
                if self.input.trim() == "quit" || self.input.trim() == "q" {
                    return EventResult::Consumed(Some(close));
                }
                self.submit();
            }
            key!(Backspace) => {
                self.input.pop();
            }
            key!(c @ ' '..='~') => self.input.push(c),
            _ => {}
        }
        EventResult::Consumed(None)
    }

    fn render(&mut self, area: Rect, surface: &mut Surface, ctx: &mut Context) {
        let theme = &ctx.editor.theme;
        let bg = theme.get("ui.background");
        let text_style = theme.get("ui.text");
        let cmd_style = theme.get("ui.linenr");
        let prompt_style = theme.get("ui.text.focus");

        surface.clear_with(area, bg);
        if area.width < 20 || area.height < 6 {
            return;
        }
        let ox = area.x + 1;
        let width = area.width.saturating_sub(2) as usize;
        let input_y = area.y + area.height - 1;

        let visible = (area.height as usize).saturating_sub(1);
        let start = self.log.len().saturating_sub(visible);
        for (i, line) in self.log[start..].iter().enumerate() {
            let mut s = line.clone();
            if s.chars().count() > width {
                s = s.chars().take(width).collect();
            }
            let style = if line.starts_with('>') {
                cmd_style
            } else {
                text_style
            };
            surface.set_string(ox, area.y + i as u16, &s, style);
        }
        let mut prompt = format!("> {}", self.input);
        if prompt.chars().count() > width {
            prompt = prompt
                .chars()
                .skip(prompt.chars().count() - width)
                .collect();
        }
        surface.set_string(ox, input_y, &prompt, prompt_style);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn world_data_is_consistent() {
        assert_eq!(ROOMS.len(), 105);
        assert_eq!(MAP.len(), 105);
        assert_eq!(ROOM_OBJECTS.len(), 105);
        assert_eq!(OBJECTS.len(), 28);
    }

    #[test]
    fn start_room_is_the_dead_end_with_the_shovel() {
        let g = Game::new();
        assert_eq!(g.room, START_ROOM);
        assert_eq!(ROOMS[g.room].1, "Dead end");
        // Object 0 is the shovel, placed at the dead end.
        assert!(g.room_objects[START_ROOM].contains(&0));
    }

    #[test]
    fn moving_east_follows_the_real_exit_matrix() {
        let mut g = Game::new();
        // dungeon-map row 1: east leads to room 2 (E/W Dirt road).
        assert_eq!(MAP[1][2], 2);
        g.go(2); // east
        assert_eq!(g.room, 2);
        assert_eq!(ROOMS[g.room].1, "E/W Dirt road");
    }

    #[test]
    fn blocked_and_special_exits_refuse() {
        let mut g = Game::new();
        // North from the dead end is blocked (-1).
        assert_eq!(MAP[1][0], -1);
        assert_eq!(g.go(0), vec!["You can't go that way.".to_string()]);
        assert_eq!(g.room, 1, "a blocked move does not move you");
    }

    #[test]
    fn take_then_drop_moves_the_object() {
        let mut g = Game::new();
        assert_eq!(g.take("shovel"), "Taken.");
        assert!(g.inventory.contains(&0));
        assert!(!g.room_objects[1].contains(&0));
        assert_eq!(g.drop("shovel"), "Dropped.");
        assert!(g.room_objects[1].contains(&0));
        assert!(g.inventory.is_empty());
    }

    #[test]
    fn scenery_cannot_be_taken() {
        let mut g = Game::new();
        // "trees" or similar scenery resolves to a negative object number.
        let scenery = OBJNAMES.iter().find(|(_, n)| *n < 0);
        if let Some((word, _)) = scenery {
            assert_eq!(g.take(word), "You cannot take that.");
        }
    }

    #[test]
    fn digging_needs_the_shovel_and_yields_buried_objects_once() {
        let mut g = Game::new();
        // Room 3 (the fork, soft ground) buries object 2 (the CPU board).
        assert_eq!(DIGGABLES[3], &[2]);
        // Grab the shovel, walk to the fork: dead-end(1) -e-> 2 -e-> fork(3).
        g.take("shovel");
        g.go(2); // to room 2
        g.go(2); // to room 3 (fork)
        assert_eq!(g.room, 3);
        assert!(!g.room_objects[3].contains(&2));
        assert_eq!(g.dig(), "I think you found something.");
        assert!(g.room_objects[3].contains(&2), "the board is dug up");
        // A second dig yields nothing.
        assert_eq!(g.dig(), "Digging here reveals nothing.");
    }

    #[test]
    fn digging_without_a_shovel_fails() {
        let mut g = Game::new();
        g.go(2);
        g.go(2); // fork, but no shovel in hand
        assert_eq!(g.dig(), "You have nothing with which to dig.");
    }

    #[test]
    fn building_front_needs_the_key() {
        // Room 5 (building-front) has a 255 exit into room 8, gated on the key.
        let mut g = Game::new();
        assert!(MAP[5].contains(&255));
        g.room = 5;
        let dir = MAP[5].iter().position(|&d| d == 255).unwrap();
        // Without the key it refuses; with the key you enter room 8.
        assert_eq!(
            g.go(dir),
            vec!["You don't have a key that can open this door.".to_string()]
        );
        g.inventory.push(OBJ_KEY);
        g.go(dir);
        assert_eq!(g.room, 8);
    }

    #[test]
    fn combination_lock_gates_the_gamma_room() {
        let mut g = Game::new();
        g.room = 32;
        let dir = MAP[32].iter().position(|&d| d == 255).unwrap();
        g.go(dir);
        assert!(g.awaiting_combo);
        assert_eq!(
            g.command("000"),
            vec!["Sorry, that combination is incorrect.".to_string()]
        );
        // Correct combo enters the gamma computing center (room 57).
        g.room = 32;
        g.go(dir);
        g.command("633");
        assert_eq!(g.room, 57);
    }

    #[test]
    fn the_bear_is_fatal() {
        let mut g = Game::new();
        g.room = 7; // bear-hangout, the bear (-3) starts here
        assert!(g.here(OBJ_BEAR));
        let dir = MAP[7].iter().position(|&d| d == 255).unwrap();
        g.go(dir);
        assert!(g.dead.is_some(), "walking past the bear kills you");
    }

    #[test]
    fn carry_limit_is_eleven_pounds() {
        let mut g = Game::new();
        // The weight (object 8) weighs 10; put it in a room and load up so the
        // total would exceed 11.
        g.inventory = vec![0]; // shovel, 2 lbs
        g.room_objects[g.room] = vec![8]; // the 10-lb weight
        assert_eq!(g.take("weight"), "Your load would be too heavy.");
        // Empty-handed, the same weight is takeable.
        g.inventory.clear();
        assert_eq!(g.take("weight"), "Taken.");
    }

    #[test]
    fn put_key_in_box_raises_the_key_level() {
        let mut g = Game::new();
        g.inventory = vec![OBJ_KEY];
        g.room_objects[g.room] = vec![OBJ_BOX];
        let before = g.key_level;
        let msg = g.put("key", "box");
        assert!(msg.contains("explodes"));
        assert_eq!(g.key_level, before + 1);
        assert!(
            !g.inventory.contains(&OBJ_KEY),
            "key vanished from inventory"
        );
        assert!(
            g.room_objects[COMPUTER_ROOM].contains(&OBJ_KEY),
            "key reappears in computer room"
        );
    }

    #[test]
    fn put_cpu_in_computer_boots_it() {
        let mut g = Game::new();
        g.inventory = vec![OBJ_CPU];
        g.room_objects[g.room] = vec![OBJ_COMPUTER];
        assert!(g.put("cpu", "computer").contains("springs to life"));
        assert!(g.computer);
    }

    #[test]
    fn jar_only_holds_what_fits() {
        let mut g = Game::new();
        g.inventory = vec![7, 8]; // diamond fits, weight does not
        g.room_objects[g.room] = vec![OBJ_JAR];
        assert_eq!(g.put("diamond", "jar"), "Done.");
        assert!(g.jar.contains(&7));
        assert_eq!(g.put("weight", "jar"), "That will not fit in the jar.");
    }

    #[test]
    fn swimming_needs_a_life_preserver() {
        let mut g = Game::new();
        g.room = 25; // lakefront-north
        g.swim();
        assert!(g.dead.is_some(), "no preserver -> you drown");
        // With the life preserver (object 9) you cross to the far shore.
        let mut g = Game::new();
        g.room = 25;
        g.inventory.push(9);
        g.swim();
        assert_eq!(g.room, 26);
    }

    #[test]
    fn eating_non_food_is_fatal() {
        let mut g = Game::new();
        g.inventory = vec![0]; // the shovel
        assert!(g.eat("shovel").contains("choking"));
        assert!(g.dead.is_some());
        // Food is edible.
        let mut g = Game::new();
        g.inventory = vec![3];
        assert_eq!(g.eat("food"), "That tasted horrible.");
        assert!(!g.inventory.contains(&3));
    }

    #[test]
    fn switch_toggles_the_black_light() {
        let mut g = Game::new();
        g.room_objects[g.room] = vec![-24]; // obj-switch
        assert_eq!(g.press("switch"), "The button is now in the on position.");
        assert!(g.black);
        assert_eq!(g.press("switch"), "The button is now in the off position.");
        assert!(!g.black);
    }

    #[test]
    fn breaking_needs_the_axe_and_kills_on_held_objects() {
        let mut g = Game::new();
        // No axe -> refuse.
        g.inventory = vec![0];
        g.room_objects[g.room] = vec![7];
        assert_eq!(
            g.break_obj("diamond"),
            vec!["You have nothing you can use to break things.".to_string()]
        );
        // With the axe, breaking a held object is fatal.
        g.inventory = vec![14, 7];
        assert!(g
            .break_obj("diamond")
            .iter()
            .any(|l| l.contains("bleed to death")));
        assert!(g.dead.is_some());
        // With the axe, a regular object in the room is destroyed.
        let mut g = Game::new();
        g.inventory = vec![14];
        g.room_objects[g.room] = vec![7];
        assert!(g.break_obj("diamond")[0].contains("million pieces"));
        assert!(!g.room_objects[g.room].contains(&7));
    }

    #[test]
    fn drive_requires_the_bus() {
        let mut g = Game::new();
        assert_eq!(g.drive(), "You cannot drive when you aren't in a vehicle.");
        g.inbus = true;
        assert!(g.drive().contains("give a direction"));
    }

    #[test]
    fn command_parses_directions_and_verbs() {
        let mut g = Game::new();
        // Take the shovel here in the start room, then walk east.
        assert_eq!(g.command("take shovel"), vec!["Taken.".to_string()]);
        assert!(g.command("inventory").iter().any(|l| l.contains("shovel")));
        let out = g.command("east");
        assert!(out.iter().any(|l| l.contains("dirt road")));
    }
}
