//! 5x5 — the zemacs port of GNU Emacs `5x5`, the light-flipping puzzle.
//!
//! A 5x5 grid of cells. Pressing a cell toggles it and its four orthogonal
//! neighbours (the "cross" / Lights-Out mechanic). The goal is to light every
//! cell. Cursor with the arrows or `hjkl`; `SPC`/`RET` presses; `n` deals a new
//! board; `r` resets the current board; `q`/`Esc` quits. Keys map to their
//! `5x5` counterparts (parsed into a `fivex5` keymap mode by
//! `scripts/gen_port_report.py`). The board logic is pure and unit-tested below.

use tui::buffer::Buffer as Surface;
use zemacs_view::graphics::Rect;

use crate::{
    compositor::{Callback, Component, Compositor, Context, Event, EventResult},
    ctrl, key,
};

const N: usize = 5;

/// The pure 5x5 board: a grid of on/off cells plus the mechanic that flips a
/// cell and its orthogonal neighbours. No I/O, no rendering — unit-tested.
#[derive(Clone)]
pub struct Board {
    cells: [[bool; N]; N],
    /// Deterministic LCG state used to deal new boards (no external RNG so the
    /// game is reproducible and testable).
    seed: u64,
}

impl Board {
    /// Deal a board from `seed`. The board is generated by starting from all-lit
    /// (the solved state) and pressing a pseudo-random set of cells, so it is
    /// always solvable — mirroring how Emacs `5x5` produces a winnable grid.
    pub fn from_seed(seed: u64) -> Self {
        let mut b = Board {
            cells: [[true; N]; N],
            seed,
        };
        // Scramble from the solved state with a deterministic number of presses.
        let mut s = seed | 1;
        for _ in 0..(12 + (seed % 8)) {
            s = s.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            let r = ((s >> 33) as usize) % N;
            let c = ((s >> 17) as usize) % N;
            b.press(r, c);
        }
        // A fully-solved deal is boring; nudge it if the scramble cancelled out.
        if b.is_won() {
            b.press(2, 2);
        }
        b.seed = seed;
        b
    }

    fn toggle(&mut self, r: usize, c: usize) {
        self.cells[r][c] = !self.cells[r][c];
    }

    /// Press cell `(r, c)`: flip it and its up/down/left/right neighbours.
    pub fn press(&mut self, r: usize, c: usize) {
        if r >= N || c >= N {
            return;
        }
        self.toggle(r, c);
        if r > 0 {
            self.toggle(r - 1, c);
        }
        if r + 1 < N {
            self.toggle(r + 1, c);
        }
        if c > 0 {
            self.toggle(r, c - 1);
        }
        if c + 1 < N {
            self.toggle(r, c + 1);
        }
    }

    /// Won when every cell is lit.
    pub fn is_won(&self) -> bool {
        self.cells.iter().flatten().all(|&on| on)
    }

    /// Number of lit cells (shown in the status line).
    pub fn lit(&self) -> usize {
        self.cells.iter().flatten().filter(|&&on| on).count()
    }
}

/// The interactive 5x5 overlay.
pub struct FiveByFive {
    board: Board,
    /// Cursor position (row, col).
    cur: (usize, usize),
    /// Presses made on the current deal.
    moves: u32,
    /// Which deal this is (advances the seed on `n`).
    deal: u64,
    start: Board,
}

impl FiveByFive {
    pub fn new() -> Self {
        let board = Board::from_seed(1);
        FiveByFive {
            start: board.clone(),
            board,
            cur: (N / 2, N / 2),
            moves: 0,
            deal: 1,
        }
    }

    fn deal_new(&mut self) {
        self.deal = self.deal.wrapping_add(1);
        self.board = Board::from_seed(self.deal);
        self.start = self.board.clone();
        self.moves = 0;
        self.cur = (N / 2, N / 2);
    }

    fn reset(&mut self) {
        self.board = self.start.clone();
        self.moves = 0;
        self.cur = (N / 2, N / 2);
    }

    fn press_here(&mut self) {
        if self.board.is_won() {
            return;
        }
        let (r, c) = self.cur;
        self.board.press(r, c);
        self.moves += 1;
    }
}

impl Default for FiveByFive {
    fn default() -> Self {
        Self::new()
    }
}

impl Component for FiveByFive {
    fn handle_event(&mut self, event: &Event, _cx: &mut Context) -> EventResult {
        let key = match event {
            Event::Key(key) => *key,
            _ => return EventResult::Ignored(None),
        };
        let close: Callback = Box::new(|compositor: &mut Compositor, _cx| {
            compositor.pop();
        });
        match key {
            key!('q') | key!(Esc) | ctrl!('c') => return EventResult::Consumed(Some(close)),

            key!(Left) | key!('h') => {
                self.cur.1 = self.cur.1.saturating_sub(1);
            }
            key!(Right) | key!('l') => {
                self.cur.1 = (self.cur.1 + 1).min(N - 1);
            }
            key!(Up) | key!('k') => {
                self.cur.0 = self.cur.0.saturating_sub(1);
            }
            key!(Down) | key!('j') => {
                self.cur.0 = (self.cur.0 + 1).min(N - 1);
            }

            key!(' ') | key!(Enter) => self.press_here(),
            key!('n') => self.deal_new(),
            key!('r') => self.reset(),
            _ => {}
        }
        EventResult::Consumed(None)
    }

    fn render(&mut self, area: Rect, surface: &mut Surface, ctx: &mut Context) {
        let theme = &ctx.editor.theme;
        let bg = theme.get("ui.background");
        let text_style = theme.get("ui.text");
        let header_style = theme.get("ui.text.focus");
        let dim_style = theme.get("ui.linenr");
        let cursor_style = theme.get("ui.selection");
        let lit_style = theme.get("ui.text.focus");

        surface.clear_with(area, bg);
        if area.width < 24 || area.height < 12 {
            return;
        }
        let ox = area.x + 2;
        let oy = area.y + 2;
        surface.set_string(ox, area.y, "5x5 — light every cell", header_style);

        // Each cell is drawn as a 3-wide box; lit = "███", dark = " · ".
        for r in 0..N {
            for c in 0..N {
                let x = ox + (c as u16) * 4;
                let y = oy + (r as u16) * 2;
                let on = self.board.cells[r][c];
                let is_cur = self.cur == (r, c);
                let glyph = if on { "███" } else { " · " };
                let style = if is_cur {
                    cursor_style
                } else if on {
                    lit_style
                } else {
                    dim_style
                };
                surface.set_string(x, y, glyph, style);
            }
        }

        let status_y = oy + (N as u16) * 2 + 1;
        let status = if self.board.is_won() {
            format!("Solved in {} moves!  n: new  r: reset  q: quit", self.moves)
        } else {
            format!(
                "lit {}/{}   moves {}   ·  arrows/hjkl move  SPC press  n new  r reset  q quit",
                self.board.lit(),
                N * N,
                self.moves
            )
        };
        surface.set_string(ox, status_y, &status, text_style);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn press_flips_cell_and_orthogonal_neighbours() {
        let mut b = Board {
            cells: [[false; N]; N],
            seed: 0,
        };
        b.press(2, 2);
        // Centre + 4 neighbours lit, diagonals untouched.
        assert!(b.cells[2][2] && b.cells[1][2] && b.cells[3][2] && b.cells[2][1] && b.cells[2][3]);
        assert!(!b.cells[1][1] && !b.cells[3][3]);
        assert_eq!(b.lit(), 5);
    }

    #[test]
    fn corner_press_stays_in_bounds() {
        let mut b = Board {
            cells: [[false; N]; N],
            seed: 0,
        };
        b.press(0, 0);
        // Corner + its two in-bounds neighbours only.
        assert_eq!(b.lit(), 3);
        assert!(b.cells[0][0] && b.cells[0][1] && b.cells[1][0]);
    }

    #[test]
    fn pressing_twice_is_a_no_op() {
        let mut b = Board::from_seed(7);
        let before = b.clone();
        b.press(1, 3);
        b.press(1, 3);
        assert_eq!(b.cells, before.cells, "double press must cancel out");
    }

    #[test]
    fn dealt_boards_are_solvable_by_construction() {
        // from_seed scrambles the solved board with presses; replaying the same
        // presses in reverse (here: any sequence that reaches all-lit exists).
        // We at least assert a fresh deal is a valid, non-panicking board.
        for seed in 0..8 {
            let b = Board::from_seed(seed);
            assert!(b.lit() <= N * N);
        }
    }

    #[test]
    fn all_lit_is_won() {
        let b = Board {
            cells: [[true; N]; N],
            seed: 0,
        };
        assert!(b.is_won());
    }
}
