//! Spook phrase list — the NSA line-eater keyword corpus from GNU Emacs
//! 30.2 `etc/spook.lines`, parsed with the faithful `cookie-snarf` rule
//! (discard the header before the first NUL, split remaining entries on
//! NUL, strip surrounding whitespace). Generated; do not edit by hand.

/// Every spook phrase, in file order. `spook` shuffles and inserts 15.
pub const PHRASES: &[&str] = &[
    "$400 million in gold bullion",
    "[Hello to all my friends and fans in domestic surveillance]",
    "22nd SAS",
    "2600",
    "2600 Magazine",
    "64 Vauxhall Cross",
    "9705 Samford Road",
    "9/11",
    "Abbas",
    "Abu Ghraib",
    "Abu Sayyaf",
    "ACC",
    "Active",
    "ADIU",
    "Adriatic",
    "advise",
    "advisors",
    "Afghanistan",
    "afsatcom",
    "AFSPC",
    "Agent",
    "Agfa",
    "Agriculture",
    "Agro",
    "Agro Terror",
    "AGT. AMME",
    "AHPCRC",
    "Aid",
    "AIEWS",
    "AIMSX",
    "Air borne",
    "airframe",
    "Air Marshal",
    "Airplane",
    "Airport",
    "AK-47",
    "Al Jazeera",
    "Al-Qaeda",
    "Al Qaeda Arabian Peninsula",
    "Al Qaeda in the Islamic Maghreb",
    "al-Qaida",
    "al-Qa'ida",
    "Al Qaida",
    "Al Qa'ida",
    "Al-Shabaab",
    "Aladdin",
    "Albania",
    "Albanian",
    "Albright",
    "Alcohol Tobacco and Firearms",
    "Aldergrove",
    "Alica",
    "AMEMB",
    "Amherst",
    "Ammonium nitrate",
    "ammunition",
    "AMTRAK",
    "AMW",
    "analyzer",
    "anarchy",
    "ANC",
    "ANDVT",
    "Anonymous",
    "Ansar al-Islam",
    "anthrax",
    "Antiviral",
    "ANZUS",
    "AOL TOS",
    "AQAP",
    "AQIM",
    "ARC",
    "Archives",
    "Area 51",
    "Arellano-Felix",
    "argus",
    "Armani",
    "Armed Revolutionary Forces Colombia",
    "Arnett",
    "ARPA",
    "arrangements",
    "Artistic Assassins",
    "ASDIC",
    "ASIO",
    "ASIS",
    "ASLET",
    "ASO",
    "ASPIC",
    "assassinate",
    "assassination",
    "asset",
    "AT&T",
    "ATF",
    "Atlas",
    "Attack",
    "Attorney General",
    "Audiotel",
    "Austin",
    "Authorities",
    "AUTODIN",
    "Avalanche",
    "Avian",
    "AVIP",
    "AVN",
    "Axis of Evil",
    "B.D.M.",
    "Bacteria",
    "bank",
    "Baranyi",
    "Barrio Azteca",
    "BART",
    "basement",
    "Basque Separatists",
    "BATF",
    "BBE",
    "BCCI",
    "bce",
    "beanpole",
    "BECCA",
    "Becker",
    "Belknap",
    "Bellcore",
    "Beltran-Leyva",
    "bemd",
    "benelux",
    "Beyond Hope",
    "BfV",
    "Bin Laden",
    "Biological",
    "Biological event",
    "Biological infection",
    "Biological weapon",
    "BITNET",
    "blackjack",
    "Blackout",
    "Black Cube",
    "Black out",
    "black-bag",
    "Black-Ops",
    "Blackbird",
    "Blacklisted 411",
    "Blackmednet",
    "Blacknet",
    "Bletchley Park",
    "Blister agent",
    "Blizzard",
    "Blowfish",
    "Blowpipe",
    "BLU-114/B",
    "BLU-97 A/B",
    "bluebird",
    "BMDO",
    "BND",
    "Body scanner",
    "bomb",
    "Bomb squad",
    "Bomb threat",
    "bootleg",
    "BOP",
    "Border",
    "Border Patrol",
    "Bosnia",
    "BOSS",
    "Botnet",
    "botux",
    "Breach",
    "Bridge",
    "brigand",
    "BRLO",
    "broadside",
    "BROMURE",
    "Brownout",
    "Brown out",
    "Brush fire",
    "Brute forcing",
    "Bruxelles",
    "bullion",
    "Burn",
    "Burst",
    "Bush Wired",
    "Bust",
    "BVD",
    "BZ",
    "Cable & Wireless",
    "Cain and Abel",
    "Calderon",
    "Cancelled",
    "CANSLO",
    "Cap-Stun",
    "Capricorn",
    "Car bomb",
    "Cartel",
    "Cartel de Golfo",
    "CATO",
    "CBM",
    "CBNRC",
    "CBOT",
    "CBP",
    "CCC",
    "CCS",
    "CDA",
    "CDC",
    "cdi",
    "CDMA",
    "Center for Disease Control",
    "Central Intelligence Agency",
    "Centro",
    "Ceridian",
    "CESID",
    "CFC",
    "chaining",
    "chameleon man",
    "Chan",
    "Chelsea",
    "Chemical",
    "Chemical agent",
    "Chemical burn",
    "Chemical fire",
    "Chemical spill",
    "Chemical weapon",
    "Chicago Posse",
    "China",
    "Chobetsu",
    "CIA",
    "CID",
    "CIDA",
    "CIKR",
    "CIM",
    "CIO",
    "CipherTAC-2000",
    "CIS",
    "CISE",
    "CISU",
    "Ciudad Juarez",
    "clandestine",
    "class struggle",
    "Clinton",
    "clones",
    "Closure",
    "Cloud",
    "CNCIS",
    "Coast Guard",
    "Cocaine",
    "COCOT",
    "Coderpunks",
    "codes",
    "Cohiba",
    "Collapse",
    "Colombia",
    "colonel",
    "Comirex",
    "Commecen",
    "Communications infrastructure",
    "Competitor",
    "Compsec",
    "Computer infrastructure",
    "computer terrorism",
    "condor",
    "Conficker",
    "Connections",
    "constitution",
    "Consul",
    "Consular",
    "Contamination",
    "CONUS",
    "Conventional weapon",
    "Cops",
    "Cornflower",
    "corporate security",
    "COS",
    "COSCO",
    "COSMOS",
    "counter intelligence",
    "counter terrorism",
    "covert video",
    "Cowboy",
    "CQB",
    "CRA",
    "cracking",
    "Craig Livingstone",
    "Crash",
    "credit card",
    "Crest",
    "Critical infrastructure",
    "Critical Infrastructure & Key Resources",
    "Croatian",
    "Crowell",
    "cryptanalysis",
    "Crypto AG",
    "crypto anarchy",
    "cryptographic",
    "CSE",
    "csim",
    "csystems",
    "CTP",
    "CTU",
    "CUD",
    "Customs and Border Protection",
    "Cyber attack",
    "cybercash",
    "Cyber Command",
    "Cyber security",
    "Cyber terror",
    "cypherpunk",
    "Cypherpunks",
    "D-11",
    "Daisy",
    "data haven",
    "Dateline",
    "DATTA",
    "David John Oates",
    "DCJFTF",
    "DDOS",
    "DEA",
    "DEADBEEF",
    "Deaths",
    "debugging",
    "Decapitated",
    "dedicated denial of service",
    "Defcon",
    "defense information warfare",
    "Delays",
    "Delta Force",
    "Denial of service",
    "Department of Homeland Security",
    "DERA",
    "DES",
    "DEVGRP",
    "DF",
    "DHS",
    "DIA",
    "Dick Cheney",
    "dictionary",
    "digicash",
    "Dirty bomb",
    "Disaster",
    "Disaster assistance",
    "Disaster management",
    "Disaster medical assistance team",
    "distributed denial of service",
    "DITSA",
    "diwn",
    "DJC",
    "DMAT",
    "DNDO",
    "Dock",
    "doctrine",
    "DOE",
    "Dolch",
    "domestic disruption",
    "Domestic nuclear detection",
    "Domestic Nuclear Detection Office",
    "Domestic security",
    "Downing Street",
    "DRA",
    "DREC",
    "DREO",
    "Drill",
    "DRM",
    "Drug",
    "Drug Administration",
    "Drug cartel",
    "Drug Enforcement Agency",
    "Drug trade",
    "Drug war",
    "DSD",
    "DSS",
    "Duress",
    "DynCorp",
    "e-bomb",
    "e-cash",
    "E.O.D.",
    "E.T.",
    "E911",
    "EADA",
    "eavesdropping",
    "Earthquake",
    "Ebola",
    "EBS",
    "Echelon",
    "E. Coli",
    "Eco terrorism",
    "EDI",
    "EG&G",
    "Egret",
    "Electric",
    "electronic surveillance",
    "El Paso",
    "Elvis",
    "embassy",
    "emc",
    "Emergency",
    "Emergency Broadcast System",
    "Emergency Landing",
    "Emergency management",
    "Emergency response",
    "encryption",
    "enemy of the state",
    "enforcers",
    "enigma",
    "Enriched",
    "Environmental terrorist",
    "EO",
    "EOD",
    "Epidemic",
    "Ermes",
    "Erosion",
    "ESN",
    "espionage",
    "ETA",
    "Etacs",
    "eternity server",
    "EUB",
    "EuroFed",
    "Europol",
    "Euskadi ta Askatasuna",
    "Evacuation",
    "event security",
    "Exon Shell",
    "Execution",
    "Exercise",
    "explosion",
    "explosive",
    "Exposure",
    "Extreme weather",
    "Extremism",
    "Exxon",
    "FAA",
    "Facility",
    "Failure",
    "FAMS",
    "FARC",
    "Fax encryption",
    "FBI",
    "FBIS",
    "FCIC",
    "FDA",
    "FDM",
    "Fedayeen",
    "Federal Air Marshal Service",
    "Federal Aviation Administration",
    "Federal Bureau of Investigation",
    "Federal Emergency Management Agency",
    "FEMA",
    "FINCEN",
    "finks",
    "FIPS140",
    "Firefly",
    "Firewalls",
    "First responder",
    "FIS",
    "fissionable",
    "FKS",
    "FLAME",
    "Flashbangs",
    "FLETC",
    "Flintlock",
    "FLiR",
    "Flood",
    "Flu",
    "FMD",
    "FMS",
    "Food Poisoning",
    "Foot and Mouth",
    "Forest fire",
    "Forte",
    "Fortezza",
    "Fort Hancock",
    "Fort Meade",
    "fraud",
    "freedom",
    "Freeh",
    "FSB",
    "FSF",
    "Ft. Bragg",
    "Ft. Knox",
    "Ft. Meade",
    "FTS2000",
    "Fundamentalism",
    "fundamentalist",
    "Fusion Center",
    "FX",
    "FXR",
    "gamma",
    "Gang",
    "Gangs",
    "Gas",
    "Gatt",
    "Gazprom",
    "GCHQ",
    "genetic",
    "GEO",
    "GEODSS",
    "George W. Bush",
    "GEOS",
    "Geraldton",
    "GGL",
    "GIGN",
    "Gist",
    "global",
    "Glock",
    "GOE",
    "Goodwin",
    "Gorelick",
    "gorilla",
    "Gorizont",
    "government",
    "GPMG",
    "grey data",
    "Grid",
    "grom",
    "GRU",
    "GSA",
    "GSG-9",
    "GSS",
    "Guantanamo",
    "Gulf Cartel",
    "Gunfight",
    "Guppy",
    "Guzman",
    "H&K",
    "H.N.P.",
    "H1N1",
    "H5N1",
    "Hacker",
    "hackers",
    "HAHO",
    "Hail",
    "halcon",
    "Halibut",
    "HALO",
    "Hamas",
    "HAMASMOIS",
    "Harvard",
    "hate",
    "Hazardous",
    "Hazardous material incident",
    "Hazmat",
    "Help",
    "Heroin",
    "Hezbollah",
    "HIC",
    "high security",
    "Hillal",
    "HoHoCon",
    "Hollyhock",
    "Hugo Chavez",
    "Home grown",
    "Homeland Defense",
    "Homeland security",
    "Honduras",
    "Hostage",
    "HPCC",
    "HRT",
    "HTCIA",
    "Human to Animal",
    "Human to Human",
    "humint",
    "Hurricane",
    "Hutsul",
    "IACIS",
    "IB",
    "ICE",
    "ID",
    "IDEA",
    "IDF",
    "IDP",
    "IED",
    "Illegal immigrants",
    "illuminati",
    "IMF",
    "Immigration Customs Enforcement",
    "import",
    "Improvised explosive device",
    "Incident",
    "Indigo",
    "industrial espionage",
    "industrial intelligence",
    "Industrial spill",
    "Infection",
    "Influenza",
    "Information Security",
    "Information Terrorism",
    "InfoSec",
    "infowar",
    "Infrastructure security",
    "Ingram Mac-10",
    "initiative",
    "INR",
    "INS",
    "INSCOM",
    "insurgency",
    "interception",
    "Internet",
    "Interstate",
    "Intiso",
    "investigation",
    "Ionosphere",
    "IRA",
    "Iraq",
    "IRIDF",
    "Iris",
    "Irish Republican Army",
    "IRS",
    "ISA",
    "ISACA",
    "ISEC",
    "ISI",
    "Islam Abduganievich Karimov",
    "Iran",
    "Islamist",
    "ISN",
    "Israel",
    "ISS",
    "IW",
    "jack",
    "JANET",
    "Janet Reno",
    "Jasmine",
    "JAVA",
    "Jet",
    "JFK",
    "Jiang Zemin",
    "JICC",
    "jihad",
    "JITEM",
    "John Kerry",
    "JPL",
    "JSOFC3IP",
    "Juarez",
    "Juiliett Class Submarine",
    "JUWTF",
    "Jyllandsposten",
    "Kennedy",
    "keyhole",
    "Keylogger",
    "KGB",
    "Kh-11",
    "Khaddafi",
    "kibo",
    "Kidnap",
    "kilderkin",
    "kilo class",
    "KLM",
    "Kosovo",
    "l0ck",
    "LABLINK",
    "La Familia",
    "Lacrosse",
    "Law enforcement",
    "Leak",
    "Lebed",
    "LEETAC",
    "Legion of Doom",
    "Leitrim",
    "Leuken-Baden",
    "Lexis-Nexis",
    "LF",
    "Lightening",
    "Lightning",
    "Listeria",
    "LLC",
    "LLNL",
    "Lockdown",
    "lock picking",
    "Locks",
    "Lon Horiuchi",
    "Looting",
    "Los Zetas",
    "LRTS",
    "LUK",
    "lynch",
    "M-14",
    "M.P.R.I.",
    "M5",
    "M72750",
    "Mace",
    "Macintosh Firewalls",
    "Macintosh Internet",
    "Macintosh Security",
    "Mafia",
    "Magnitude",
    "Mahmoud Ahmadinejad",
    "mailbomb",
    "Majic",
    "Malware",
    "Manfurov",
    "mania",
    "Mantis",
    "Maple",
    "Mara salvatrucha",
    "Marijuana",
    "Maritime domain awarenes",
    "market",
    "MARTA",
    "Marxist",
    "Masuda",
    "Matamoros",
    "Mavricks",
    "Mayfly",
    "MCI",
    "MD2",
    "MD4",
    "MD5",
    "MDA",
    "Medco",
    "mega",
    "Mena",
    "Menwith",
    "Merlin",
    "Meta-hackers",
    "Methamphetamine",
    "Meth Lab",
    "Metro",
    "Mexican army",
    "Mexicles",
    "Mexico",
    "MF",
    "MI-17",
    "MI5",
    "MI6",
    "Michoacna",
    "Middleman",
    "military",
    "Military Intelligence",
    "militia",
    "MILSATCOM",
    "mindwar",
    "Minox",
    "MIT",
    "Mitigation",
    "MIT-LL",
    "MITM",
    "MOD",
    "MOIS",
    "mol",
    "Mole",
    "monarchist",
    "Montenegro",
    "morse",
    "Morwenstow",
    "Mossad",
    "Mossberg",
    "MP5k",
    "MP5K-SD",
    "MS13",
    "MS-13",
    "MSCJ",
    "MSEE",
    "MSNBC",
    "MSW",
    "Mudslide",
    "Mud slide",
    "munitions",
    "Mutation",
    "MYK",
    "Mysql injection",
    "NACSI",
    "Narco banners",
    "Narcos",
    "Narcotics",
    "NASA",
    "NATIA",
    "National Biosurveillance Integration Center",
    "National Guard",
    "national information infrastructure",
    "National infrastructure",
    "Nationalist",
    "National laboratory",
    "National Operations Center",
    "National preparedness",
    "National security",
    "NATO",
    "NATOA",
    "NAVWAN",
    "NAVWCWPNS",
    "Nazi",
    "NBIC",
    "NCCS",
    "NCSA",
    "Nerve agent",
    "New Federation",
    "New World Order",
    "Nigeria",
    "NIJ",
    "Nike",
    "NIMA",
    "ninja",
    "nitrate",
    "nkvd",
    "NOC",
    "NOCS",
    "Nogales",
    "NORAD",
    "Noriega",
    "North Korea",
    "Norvo Virus",
    "NRC",
    "NRL",
    "NRO",
    "NSA",
    "NSCT",
    "NSG",
    "NSP",
    "NSWC",
    "NTIS",
    "NTT",
    "nuclear",
    "Nuclear facility",
    "Nuclear threat",
    "Nuevo Leon",
    "number key",
    "NVD",
    "NWO",
    "OAU",
    "offensive information warfare",
    "oil",
    "Operation Iraqi Freedom",
    "Oratory",
    "Organized crime",
    "Ortega",
    "orthodox",
    "Osama",
    "Oscor",
    "OSS",
    "OTP",
    "outage",
    "Outbreak",
    "Pakistan",
    "Palestine Liberation Front",
    "Palestine Liberation Organization",
    "Panama",
    "Pandemic",
    "passwd",
    "password",
    "Passwords",
    "Patel",
    "PBX",
    "PCS",
    "Peering",
    "Peking",
    "PEM",
    "penrep",
    "Perl-RSA",
    "PET",
    "PFS",
    "PGP",
    "phinx",
    "pipeline",
    "Phishing",
    "Phreaking",
    "Pine Gap",
    "pink noise",
    "Pipe bomb",
    "Pirates",
    "PLA",
    "Plague",
    "Plame",
    "Plane",
    "Planet-1",
    "Platform",
    "PLF",
    "PLO",
    "Plot",
    "Plume",
    "plutonium",
    "POCSAG",
    "Police",
    "Pork",
    "Port",
    "Port Authority",
    "Power",
    "Power lines",
    "Power outage",
    "PPP",
    "PPS",
    "pre-emptive",
    "president",
    "press-release",
    "Pretoria",
    "Prevention",
    "primacord",
    "PRIME",
    "Privacy",
    "Project Monarch",
    "propaganda",
    "PSAC",
    "Pseudonyms",
    "Psyops",
    "PTT",
    "Public Health",
    "Putin",
    "Qaddafi",
    "Quarnantine",
    "quarter",
    "quiche",
    "r00t",
    "racal",
    "radar",
    "Radiation",
    "Radicals",
    "Radioactive",
    "RAID",
    "rail gun",
    "Rand Corporation",
    "Rapid Reaction",
    "RCMP",
    "rebels",
    "Recall",
    "Recce",
    "Recovery",
    "Recruitment",
    "Red Cell",
    "Red Cross",
    "red noise",
    "Reflection",
    "Relief",
    "remailers",
    "ReMOB",
    "Reno",
    "replay",
    "Resistant",
    "Response",
    "Retinal Fetish",
    "Reynosa",
    "Reyosa",
    "RFI",
    "rhost",
    "Ricin",
    "Riot",
    "RIT",
    "RL",
    "rogue",
    "Rolm",
    "Ron Brown",
    "Ronco",
    "Rootkit",
    "Roswell",
    "rs9512c",
    "RSA",
    "RSP",
    "Rubin",
    "Ruby Ridge",
    "Rule Psix",
    "Rumsfeld",
    "RUOP",
    "RX-7",
    "S Box",
    "S Key",
    "S.A.I.C.",
    "S.E.T. Team",
    "S/Key",
    "SABC",
    "SACLANT",
    "Saddam Hussein",
    "SADF",
    "SADMS",
    "SAFE",
    "Salmonella",
    "San Diego",
    "SAP",
    "SAPO",
    "SAR",
    "Sarin",
    "SASP",
    "SASR",
    "satellite imagery",
    "Saudi Arabia",
    "SBI",
    "SBIRS",
    "SBS",
    "Scammers",
    "SCIF",
    "Screening",
    "SCUD missile",
    "Scully",
    "SDI",
    "SEAL",
    "SEAL Team 6",
    "Sears Tower",
    "Secret Service",
    "secure",
    "Secure Border Initiative",
    "Secure Internet",
    "secure shell",
    "security",
    "Security Consulting",
    "Security Council",
    "Security Evaluation",
    "SEL",
    "Semtex",
    "Serbian",
    "SERT",
    "Service disruption",
    "SETA",
    "SGC",
    "SGDN",
    "SGI",
    "SHA",
    "SHAPE",
    "Shayet-13",
    "Shell",
    "Shelter-in-place",
    "SHF",
    "Shooting",
    "Shootout",
    "Shots fired",
    "Sick",
    "SIG",
    "SIGDASYS",
    "SIGDEV",
    "sigvoice",
    "SIN",
    "Sinaloa",
    "SIRC",
    "SISDE",
    "SISMI",
    "Skipjack",
    "Skytel",
    "SL-1",
    "Sleet",
    "SLI",
    "SLIP",
    "Smallpox",
    "Small Pox",
    "Smart",
    "smuggle",
    "smugglers",
    "Smuggling",
    "sneakers",
    "sniper",
    "Snow",
    "Social media",
    "Somolia",
    "SONANGOL",
    "Sonora",
    "Soros",
    "South Africa",
    "Southwest",
    "Soviet",
    "SP4",
    "Spammer",
    "Speakeasy",
    "speedbump",
    "Spetznaz",
    "spies",
    "Spillover",
    "spook",
    "spy",
    "Spyderco",
    "squib",
    "SRI",
    "ssa",
    "SSCI",
    "SSL",
    "stakeout",
    "Standford",
    "Standoff",
    "STARLAN",
    "State of emergency",
    "Stego",
    "STEP",
    "Steve Case",
    "Storm",
    "Strain",
    "Stranded",
    "strategic",
    "Stuck",
    "subversive",
    "Subway",
    "Sugar Grove",
    "Suicide attack",
    "Suicide bomber",
    "SUN",
    "Sundevil",
    "supercomputer",
    "SURVIAC",
    "SUSLO",
    "Suspicious device",
    "Suspicious package",
    "Suspicious substance",
    "SVR",
    "SWAT",
    "sweep",
    "sweeping",
    "Swine",
    "SWS",
    "Symptoms",
    "Syria",
    "Taiwan",
    "Talent",
    "Taliban",
    "Tamaulipas",
    "Tamiflu",
    "Tamil Tigers",
    "target",
    "Task Force",
    "TB",
    "TDM. SUKLO",
    "TDR",
    "TDYC",
    "Tehrik-i-Taliban Pakistan",
    "Telecommunications",
    "Telex",
    "TELINT",
    "Temblor",
    "tempest",
    "Templeton",
    "TEMPSET",
    "Terror",
    "terrorism",
    "Terrorism Defensive Information",
    "terrorist",
    "TEXTA. ELF",
    "THAAD",
    "threat",
    "Ti",
    "TIE",
    "Tijuana",
    "Tony Blair",
    "top secret",
    "Tornado",
    "Torreon",
    "Toxic",
    "Trafficking",
    "Transportation security",
    "Transportation Security Administration",
    "TRD",
    "Treasury",
    "Tremor",
    "Trojan",
    "Trump",
    "TRW",
    "TSA",
    "TSCI",
    "TSCM",
    "Tsunami",
    "Tsunami Warning Center",
    "TTP",
    "Tuberculosis",
    "Tucson",
    "TUSA",
    "TWA",
    "Twister",
    "Typhoon",
    "UDT",
    "UFO",
    "UHF",
    "UKUSA",
    "UMTS",
    "UN",
    "unclassified",
    "UNCPCJ",
    "undercover",
    "underground",
    "United Nations",
    "Unix Security",
    "UNSCOM",
    "UOP",
    "USACIL",
    "USAFA",
    "USCG",
    "U.S. Citizenship and Immigration Services",
    "USCODE",
    "USCOI",
    "U.S. Consulate",
    "USDOJ",
    "USP",
    "USSS",
    "UT/RUS",
    "utopia",
    "UTU",
    "UXO",
    "Uzbekistan",
    "Uzi",
    "Vaccine",
    "Venezuela",
    "Verisign",
    "VHF",
    "Vickie Weaver",
    "Vince Foster",
    "Vinnell",
    "Violence",
    "VIP Protection",
    "Virii",
    "virtual",
    "Virual Hemorrhagic Fever",
    "virus",
    "VLSI",
    "VNET",
    "Wackendude",
    "Wackenhut",
    "Waco, Texas",
    "Waihopai",
    "War on Terrorism",
    "warfare",
    "Warning",
    "Watch",
    "Water borne",
    "Watergate",
    "Wave",
    "Weapons cache",
    "Weapons grade",
    "weapons of mass destruction",
    "White House",
    "white noise",
    "White Powder",
    "White Water",
    "Whitehouse",
    "WHO",
    "Wildfire",
    "William Gates",
    "WINGS",
    "wire transfer",
    "WMATA",
    "world domination",
    "World Health Organization",
    "World News",
    "World Trade Center",
    "Worm",
    "xecutive",
    "XS4ALL",
    "Yakima",
    "Yemen",
    "Yobie",
    "Yukon",
    "Yuma",
    "Zachawi",
];
