//! Full custom color-scheme editor: edit per-scope foreground colors with a live
//! swatch, then save to `~/.zemacs/themes/<name>.toml` and point `config.toml` at
//! it. Colors seed from the currently-active theme on first render.

use tui::buffer::Buffer as Surface;
use zemacs_view::{
    graphics::{Color, Rect},
    input::{KeyCode, KeyEvent, MouseButton, MouseEventKind},
};

use crate::compositor::{Component, Context, Event, EventResult};

/// Curated, high-impact theme scopes exposed in the editor.
const SCOPES: &[&str] = &[
    "ui.background",
    "ui.text",
    "ui.text.focus",
    "ui.selection",
    "ui.cursor",
    "ui.window",
    "ui.statusline",
    "comment",
    "keyword",
    "function",
    "type",
    "constant",
    "string",
    "variable",
    "operator",
    "diff.plus",
    "diff.minus",
    "warning",
    "error",
];

fn theme_name() -> &'static str {
    "zemacs-custom"
}

fn hex_of(c: Option<Color>) -> String {
    match c {
        Some(Color::Rgb(r, g, b)) => format!("#{r:02x}{g:02x}{b:02x}"),
        _ => String::new(),
    }
}

pub struct ThemeEditor {
    /// (scope, hex) — seeded from the active theme on first render.
    colors: Vec<(String, String)>,
    selected: usize,
    editing: bool,
    buf: String,
    seeded: bool,
    saved_msg: bool,
    row_hits: Vec<(u16, u16, u16, usize)>,
    btn_hits: Vec<(u16, u16, u16, u8)>, // 0 = save
}

impl ThemeEditor {
    pub fn new() -> Self {
        Self {
            colors: Vec::new(),
            selected: 0,
            editing: false,
            buf: String::new(),
            seeded: false,
            saved_msg: false,
            row_hits: Vec::new(),
            btn_hits: Vec::new(),
        }
    }

    fn save(&mut self) {
        // Write a flat fg-only theme: `scope = "#rrggbb"`.
        let mut body = String::from("# Generated by the zemacs color-scheme editor\n");
        for (scope, hex) in &self.colors {
            if hex.starts_with('#') && (hex.len() == 7 || hex.len() == 4) {
                body.push_str(&format!("\"{scope}\" = \"{hex}\"\n"));
            }
        }
        let dir = zemacs_loader::config_dir().join("themes");
        let _ = std::fs::create_dir_all(&dir);
        let _ = std::fs::write(dir.join(format!("{}.toml", theme_name())), body);

        // Point config.toml at the custom theme (preserving other keys).
        let cfg_path = zemacs_loader::config_dir().join("config.toml");
        let mut cfg: toml::Value = std::fs::read_to_string(&cfg_path)
            .ok()
            .and_then(|s| toml::from_str(&s).ok())
            .unwrap_or_else(|| toml::Value::Table(Default::default()));
        if let Some(t) = cfg.as_table_mut() {
            t.insert("theme".into(), toml::Value::String(theme_name().into()));
        }
        if let Ok(s) = toml::to_string_pretty(&cfg) {
            let _ = std::fs::write(cfg_path, s);
        }
        self.saved_msg = true;
    }

    fn commit(&mut self) {
        if let Some((_, hex)) = self.colors.get_mut(self.selected) {
            let v = self.buf.trim();
            if Color::from_hex(v).is_ok() {
                *hex = v.to_string();
            }
        }
        self.editing = false;
    }

    fn handle_mouse(&mut self, col: u16, row: u16, kind: MouseEventKind) -> EventResult {
        if !matches!(kind, MouseEventKind::Down(MouseButton::Left)) {
            return EventResult::Consumed(None);
        }
        if self.btn_hits.iter().any(|&(x0, x1, r, _)| row == r && col >= x0 && col < x1) {
            self.save();
            return EventResult::Consumed(None);
        }
        if let Some(&(_, _, _, idx)) = self
            .row_hits
            .iter()
            .find(|&&(r, x0, x1, _)| row == r && col >= x0 && col < x1)
        {
            self.selected = idx;
            self.buf = self.colors.get(idx).map(|c| c.1.clone()).unwrap_or_default();
            self.editing = true;
            self.saved_msg = false;
        }
        EventResult::Consumed(None)
    }
}

impl Component for ThemeEditor {
    fn handle_event(&mut self, event: &Event, _cx: &mut Context) -> EventResult {
        let key: KeyEvent = match event {
            Event::Key(k) => *k,
            Event::Mouse(ev) => return self.handle_mouse(ev.column, ev.row, ev.kind),
            _ => return EventResult::Ignored(None),
        };
        self.saved_msg = false;
        if self.editing {
            match key.code {
                KeyCode::Esc => self.editing = false,
                KeyCode::Enter => self.commit(),
                KeyCode::Backspace => {
                    self.buf.pop();
                }
                KeyCode::Char(c) => self.buf.push(c),
                _ => {}
            }
            return EventResult::Consumed(None);
        }
        match key.code {
            KeyCode::Esc | KeyCode::Char('q') => {
                return EventResult::Consumed(Some(Box::new(|c, _| {
                    c.pop();
                })))
            }
            KeyCode::Char('j') | KeyCode::Down => {
                if !self.colors.is_empty() {
                    self.selected = (self.selected + 1) % self.colors.len();
                }
            }
            KeyCode::Char('k') | KeyCode::Up => {
                if !self.colors.is_empty() {
                    self.selected = (self.selected + self.colors.len() - 1) % self.colors.len();
                }
            }
            KeyCode::Enter => {
                self.buf = self.colors.get(self.selected).map(|c| c.1.clone()).unwrap_or_default();
                self.editing = true;
            }
            KeyCode::Char('s') => self.save(),
            _ => {}
        }
        EventResult::Consumed(None)
    }

    fn render(&mut self, area: Rect, surface: &mut Surface, ctx: &mut Context) {
        use crate::ui::rat::{render, to_rat_style};
        use ratatui::style::{Modifier as RMod, Style as RStyle};
        use ratatui::text::Span;
        use ratatui::widgets::{Block, BorderType, Borders, Paragraph};

        if !self.seeded {
            self.colors = SCOPES
                .iter()
                .map(|s| (s.to_string(), hex_of(ctx.editor.theme.get(s).fg)))
                .collect();
            self.seeded = true;
        }
        self.row_hits.clear();
        self.btn_hits.clear();

        let theme = &ctx.editor.theme;
        let bg = to_rat_style(theme.get("ui.background"));
        let text = to_rat_style(theme.get("ui.text"));
        let dim = to_rat_style(theme.get("comment"));
        let border = to_rat_style(theme.get("ui.window"));
        let accent = to_rat_style(theme.get("function")).add_modifier(RMod::BOLD);
        surface.clear_with(area, theme.get("ui.background"));

        let frame = Block::default()
            .borders(Borders::ALL)
            .border_type(BorderType::Rounded)
            .border_style(border)
            .style(bg)
            .title(Span::styled(" Color Scheme — custom theme ", accent));
        render(frame, area, surface);
        let inner = Rect::new(area.x + 2, area.y + 1, area.width.saturating_sub(4), area.height.saturating_sub(2));
        if inner.width < 10 || inner.height < 5 {
            return;
        }

        // save button
        let label = if self.saved_msg { " ✓ Saved → restart to apply " } else { " 💾 Save theme " };
        let w = label.chars().count() as u16;
        render(
            Paragraph::new(Span::styled(label, text.add_modifier(RMod::REVERSED))),
            Rect::new(inner.x, inner.y, w, 1),
            surface,
        );
        self.btn_hits.push((inner.x, inner.x + w, inner.y, 0));

        // scope rows: name | #hex | swatch
        let list_y = inner.y + 2;
        let hex_x = inner.x + 24.min(inner.width / 2);
        let swatch_x = hex_x + 10;
        for (i, (scope, hex)) in self.colors.iter().enumerate() {
            let row = list_y + i as u16;
            if row >= inner.y + inner.height - 1 {
                break;
            }
            let is_sel = i == self.selected;
            if is_sel {
                surface.set_style(Rect::new(inner.x, row, inner.width, 1), theme.get("ui.selection"));
            }
            render(
                Paragraph::new(Span::styled(scope.clone(), if is_sel { accent } else { text })),
                Rect::new(inner.x + 1, row, hex_x - inner.x - 2, 1),
                surface,
            );
            let shown = if is_sel && self.editing { format!("{}▏", self.buf) } else { hex.clone() };
            render(
                Paragraph::new(Span::styled(shown, text.add_modifier(RMod::UNDERLINED))),
                Rect::new(hex_x, row, 9, 1),
                surface,
            );
            // live swatch using the typed/stored color
            let cur = if is_sel && self.editing { self.buf.as_str() } else { hex.as_str() };
            if let Ok(Color::Rgb(r, g, b)) = Color::from_hex(cur) {
                let sw = RStyle::default().bg(ratatui::style::Color::Rgb(r, g, b));
                render(Paragraph::new(Span::styled("        ", sw)), Rect::new(swatch_x, row, 8, 1), surface);
            }
            self.row_hits.push((row, inner.x, inner.x + inner.width, i));
        }

        let help = if self.editing {
            " type a #rrggbb hex · ⏎ apply · Esc cancel"
        } else {
            " j/k move · ⏎/click edit color · s save theme"
        };
        render(
            Paragraph::new(Span::styled(help, dim)),
            Rect::new(inner.x, inner.y + inner.height - 1, inner.width, 1),
            surface,
        );
    }
}
