#!/usr/bin/env python3
"""Generate `zmax-core/src/unicode_names.txt` — the Unicode character names.

Emacs reads a character by name (`C-x 8 RET`, `isearch-char-by-name`) and reports
one for a character (`emoji-describe`'s fallback). Both need the name table.

Only the *listed* names go in the file. Unicode specifies the rest by rule —
`CJK UNIFIED IDEOGRAPH-4E00` and the Hangul syllables are derived from the
codepoint (UAX #44 name-derivation rules NR1 and NR2) — and deriving them in code
keeps 110,720 entries out of the repo.

The source is CPython's own `unicodedata`, which is the Unicode Character
Database; the file records which version it was generated from so a mismatch is
visible rather than silent.

Run: python3 scripts/gen_unicode_names.py
"""

import os
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "zmax-core", "src", "unicode_names.txt")


def is_derived(cp: int, name: str) -> bool:
    """Whether `name` follows one of Unicode's derivation rules, so the lookup
    can compute it instead of storing it."""
    # NR1: Hangul syllables, composed from the jamo short names.
    if name.startswith("HANGUL SYLLABLE "):
        return True
    # NR2: a fixed prefix followed by the codepoint in hex.
    return name.endswith("-%04X" % cp) or name.endswith("-%05X" % cp)


def main() -> None:
    lines = ["# Generated by scripts/gen_unicode_names.py — do not edit.",
             "# Unicode %s. One `HEX;NAME` per line, ascending by codepoint."
             % unicodedata.unidata_version]
    for cp in range(0x110000):
        try:
            name = unicodedata.name(chr(cp))
        except ValueError:
            continue
        if is_derived(cp, name):
            continue
        lines.append("%04X;%s" % (cp, name))
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")
    print("wrote %s (%d names, Unicode %s)"
          % (OUT, len(lines) - 2, unicodedata.unidata_version))


if __name__ == "__main__":
    main()
