#!/usr/bin/env perl
# Generate zmax-term/src/vim_option_scopes.rs from neovim's src/nvim/options.lua:
# for every option, its scope and the flags `:mksession`/`:mkvimrc` read
# (`makeset` in option.c). Usage:
#   scripts/gen_vim_option_scopes.pl path/to/options.lua > zmax-term/src/vim_option_scopes.rs
use strict;
use warnings;

my $src = do { local $/; <> };
my @rows;
# Each option is a `{ ... }` table holding `full_name = '…'`.
while ($src =~ /\n    \{\n(.*?)\n    \},/gs) {
    my $body = $1;
    my ($name) = $body =~ /full_name = '([^']+)'/ or next;
    my ($abbr) = $body =~ /abbreviation = '([^']+)'/;
    my ($scope) = $body =~ /scope = \{([^}]*)\}/;
    my @scope = $scope =~ /'(\w+)'/g;
    my %flag = map { $_ => ($body =~ /\b$_ = true/ ? 1 : 0) } qw(no_mkrc pri_mkrc noglob immutable);
    my ($type) = $body =~ /\btype = '(\w+)'/;
    my $expand = $body =~ /\bexpand = / ? 1 : 0;
    my ($list) = $body =~ /\blist = '(\w+)'/;
    $list //= '';
    my $nodup = $body =~ /\bdeny_duplicates = true/ ? 1 : 0;
    push @rows, sprintf(
        "    VimOptionScope { name: %-20s abbr: %-10s scope: %-14s kind: %-8s no_mkrc: %-5s pri_mkrc: %-5s noglob: %-5s immutable: %-5s expand: %-5s comma: %-5s one_comma: %-5s colon: %-5s flag_list: %-5s no_dup: %s },",
        "\"$name\",", '"' . ($abbr // '') . '",', 'Scope::' . scope_name(@scope) . ',',
        'Kind::' . ucfirst($type // 'string') . ',',
        bool($flag{no_mkrc}) . ',', bool($flag{pri_mkrc}) . ',', bool($flag{noglob}) . ',',
        bool($flag{immutable}) . ',', bool($expand) . ',',
        bool($list =~ /comma/) . ',', bool($list =~ /^onecomma/) . ',', bool($list =~ /colon$/) . ',',
        bool($list =~ /^flags/) . ',', bool($nodup));
}
sub bool { $_[0] ? 'true' : 'false' }
sub scope_name {
    my $s = join ',', @_;
    return { 'global' => 'Global', 'buf' => 'Buf', 'win' => 'Win',
             'global,buf' => 'GlobalBuf', 'global,win' => 'GlobalWin' }->{$s}
        // die "unknown scope $s";
}
print <<"HEAD";
// Generated by scripts/gen_vim_option_scopes.pl from neovim's
// src/nvim/options.lua — do not edit by hand. Each option's scope and the
// flags `makeset` (option.c) reads when `:mksession` writes options.

/// Where an option's value lives (`scope` in options.lua).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Scope {
    Global,
    Buf,
    Win,
    /// Global with a buffer-local value (`:setlocal` overrides).
    GlobalBuf,
    /// Global with a window-local value.
    GlobalWin,
}

/// The option's value type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    Boolean,
    Number,
    String,
}

#[derive(Debug, Clone, Copy)]
pub struct VimOptionScope {
    pub name: &'static str,
    pub abbr: &'static str,
    pub scope: Scope,
    pub kind: Kind,
    /// Never written by `:mksession`/`:mkvimrc` (`kOptFlagNoMkrc`).
    pub no_mkrc: bool,
    /// Written before the others (`kOptFlagPriMkrc`).
    pub pri_mkrc: bool,
    /// Never written as a global value (`kOptFlagNoGlob`).
    pub noglob: bool,
    /// Cannot change, so never differs from its default.
    pub immutable: bool,
    /// A path-like value, written with `~` for the home directory
    /// (`kOptFlagExpand`).
    pub expand: bool,
    /// A comma-separated list (`kOptFlagComma`).
    pub comma: bool,
    /// A comma list without empty items (`kOptFlagOneComma`).
    pub one_comma: bool,
    /// Items are `key:value` (`kOptFlagColon`).
    pub colon: bool,
    /// A list of single-character flags (`kOptFlagFlagList`).
    pub flag_list: bool,
    /// No duplicate items (`kOptFlagNoDup`).
    pub no_dup: bool,
}

// One aligned row per option; rustfmt would split every field onto its own line.
#[rustfmt::skip]
pub const VIM_OPTION_SCOPES: &[VimOptionScope] = &[
HEAD
print "$_\n" for @rows;
print "];\n";
