#!/usr/bin/env python3
"""Parse the Emacs-dumped dunnet data (canonical Lisp from prin1) into a Rust
data module. The data was resolved by Emacs itself (obj-* constants -> numbers),
so this is a faithful transcription of dunnet.el's world, not a reconstruction."""
import sys, re

SRC = sys.argv[1]
OUT = sys.argv[2]

text = open(SRC, encoding="utf-8").read()
sections = {}
cur = None
buf = []
for line in text.split("\n"):
    m = re.match(r"===(.+)===$", line)
    if m:
        if cur:
            sections[cur] = "\n".join(buf)
        cur = m.group(1)
        buf = []
    else:
        buf.append(line)
if cur:
    sections[cur] = "\n".join(buf)


# --- a small reader for the subset of Lisp that prin1 emits here ---
class Reader:
    def __init__(self, s):
        self.s = s
        self.i = 0

    def peek(self):
        return self.s[self.i] if self.i < len(self.s) else ""

    def skip_ws(self):
        while self.i < len(self.s) and self.s[self.i] in " \t\n\r":
            self.i += 1

    def read(self):
        self.skip_ws()
        c = self.peek()
        if c == "(":
            return self.read_list()
        if c == '"':
            return self.read_string()
        return self.read_atom()

    def read_list(self):
        self.i += 1  # (
        out = []
        while True:
            self.skip_ws()
            if self.peek() == ")":
                self.i += 1
                return out
            if self.peek() == ".":  # dotted pair: (a . b)
                # only appears as (sym . int); treat as 2-tuple marker
                self.i += 1
                self.skip_ws()
                out.append(("__dot__", self.read()))
                continue
            out.append(self.read())

    def read_string(self):
        self.i += 1  # opening "
        out = []
        while self.i < len(self.s):
            c = self.s[self.i]
            if c == "\\":
                out.append(self.s[self.i + 1])
                self.i += 2
                continue
            if c == '"':
                self.i += 1
                return ("str", "".join(out))
            out.append(c)
            self.i += 1
        raise ValueError("unterminated string")

    def read_atom(self):
        j = self.i
        while self.i < len(self.s) and self.s[self.i] not in " \t\n\r()":
            self.i += 1
        tok = self.s[j:self.i]
        if tok == "nil":
            return None
        if re.fullmatch(r"-?\d+", tok):
            return ("int", int(tok))
        return ("sym", tok)


def parse(name):
    return Reader(sections[name].strip()).read()


rooms = parse("dun-rooms")            # [ [ (str,long),(str,short) ], ... ]
dmap = parse("dungeon-map")           # [ [ (int,..)*12 ], ... ]
objects = parse("dun-objects")        # [ [ (str),(str) ], ... ]
obj_lbs = parse("dun-object-lbs")     # [ (int,..) ]
obj_pts = parse("dun-object-pts")     # [ (int,..) ]
room_objs = parse("dun-room-objects") # [ None | [ (int,..) ], ... ]
perm = parse("dun-perm-objects")      # [ [ (str)|None ... ], ... ]
objnames = parse("dun-objnames")      # [ [ (sym,name), (__dot__,(int,n)) ], ... ]
diggables = parse("dun-diggables")    # [ None | [ (int,..) ], ... ]


def s(x):
    """A Lisp ("str", value) -> a Rust string literal."""
    v = x[1] if isinstance(x, tuple) and x[0] == "str" else ""
    v = v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
    return '"%s"' % v


def i(x):
    return x[1] if isinstance(x, tuple) and x[0] == "int" else 0


L = []
L.append("//! Dunnet world data — transcribed faithfully from GNU Emacs 30.2")
L.append("//! `lisp/play/dunnet.el` by loading it in Emacs batch and dumping the")
L.append("//! resolved constants (so `obj-*` symbols are real indices). Generated by")
L.append("//! scripts/gen_dunnet_data.py; do not edit by hand.")
L.append("")
L.append("/// Each room: (long description, short name). Indexed by room number.")
L.append("pub const ROOMS: &[(&str, &str)] = &[")
for r in rooms:
    L.append("    (%s, %s)," % (s(r[0]), s(r[1])))
L.append("];")
L.append("")
L.append("/// Exit matrix: MAP[room] = [N,S,E,W,NE,SE,NW,SW,Up,Down,In,Out].")
L.append("/// -1 = no exit; 255 = a special/puzzle exit; else destination room.")
L.append("pub const MAP: &[[i16; 12]] = &[")
for row in dmap:
    L.append("    [%s]," % ", ".join(str(i(x)) for x in row))
L.append("];")
L.append("")
L.append("/// Regular objects: (room description, inventory name). Indexed by object number.")
L.append("pub const OBJECTS: &[(&str, &str)] = &[")
for o in objects:
    L.append("    (%s, %s)," % (s(o[0]), s(o[1])))
L.append("];")
L.append("")
L.append("/// Object weights (pounds) and treasure points, indexed by object number.")
L.append("pub const OBJ_LBS: &[i16] = &[%s];" % ", ".join(str(i(x)) for x in obj_lbs))
L.append("pub const OBJ_PTS: &[i16] = &[%s];" % ", ".join(str(i(x)) for x in obj_pts))
L.append("")
L.append("/// Initial objects per room (first 105 slots = rooms). Negative = a fixed")
L.append("/// scenery object (see PERM_OBJECTS by absolute value); 255 = a special.")
L.append("pub const ROOM_OBJECTS: &[&[i16]] = &[")
for entry in room_objs[:105]:
    if entry is None:
        L.append("    &[],")
    else:
        L.append("    &[%s]," % ", ".join(str(i(x)) for x in entry))
L.append("];")
L.append("")
L.append("/// Fixed scenery descriptions, indexed by the absolute value of a negative")
L.append("/// object number.")
L.append("pub const PERM_OBJECTS: &[&str] = &[")
for p in perm:
    if p is None or (isinstance(p, list) and (not p or p[0] is None)):
        L.append('    "",')
    else:
        first = p[0] if isinstance(p, list) else p
        L.append("    %s," % s(first))
L.append("];")
L.append("")
L.append("/// Objects revealed by digging in each room (empty = nothing to dig up).")
L.append("pub const DIGGABLES: &[&[i16]] = &[")
for entry in diggables:
    if entry is None:
        L.append("    &[],")
    else:
        L.append("    &[%s]," % ", ".join(str(i(x)) for x in entry))
L.append("];")
L.append("")
L.append("/// How the player may name objects: (word, object number). Negative numbers")
L.append("/// are scenery/permanent objects.")
L.append("pub const OBJNAMES: &[(&str, i16)] = &[")
for pair in objnames:
    # pair == [ ("sym", name), ("__dot__", ("int", n)) ]
    name = pair[0][1]
    num = pair[1][1][1]
    L.append('    ("%s", %d),' % (name, num))
L.append("];")
L.append("")

open(OUT, "w", encoding="utf-8").write("\n".join(L))
print("rooms=%d map=%d objects=%d room_objects=%d perm=%d objnames=%d"
      % (len(rooms), len(dmap), len(objects), min(105, len(room_objs)), len(perm), len(objnames)))
