//! A viminfo-format dump of editor state, written to `<config-dir>/.zmaxinfo`
//! (i.e. `~/.zmax/.zmaxinfo`) so that external tools — including ones that
//! already parse Vim's `~/.viminfo` — can read zmax's recent files, marks,
//! jumplist, registers, and command/search history without any new format.
//!
//! The layout matches Vim 9.x byte-for-byte: each section has the same comment
//! header, the same human-readable lines, and the same machine-readable `|`
//! "bar lines" Vim emits. Sections zmax has no equivalent for (expression /
//! input / debug history) are written empty, exactly as Vim does when they hold
//! nothing.
//!
//! The mapping from zmax state to Vim's model:
//!   * File marks `'0`-`'9` ← the recent-files MRU list (newest = `'0`), with the
//!     cursor position of any matching open buffer (else line 1, col 0).
//!   * Jumplist ← the focused view's jump list (newest first).
//!   * Per-file marks (`> path` blocks) ← each open document's marks.
//!   * Command Line History ← the `:` register; Search String History ← `/`.
//!   * Registers ← the named/numbered registers (`:`/`/`/clipboard excluded).
//!
//! Vim stores a real per-entry timestamp; zmax does not track one, so every
//! entry is stamped with the save time. Written on exit (see `Application::run`).

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use zmax_core::coords_at_pos;
use zmax_view::Editor;

const FILE_NAME: &str = ".zmaxinfo";

fn store_path() -> PathBuf {
    zmax_loader::config_dir().join(FILE_NAME)
}

/// The home directory, derived from the config dir (`<home>/.zmax`), so paths
/// can be tildified the way Vim writes them.
fn home_dir() -> Option<PathBuf> {
    zmax_loader::config_dir().parent().map(|p| p.to_path_buf())
}

fn now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Build the `.zmaxinfo` content from live editor state and write it to disk.
pub fn save(editor: &Editor) {
    let body = render(editor, now(), home_dir().as_deref());
    let path = store_path();
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let _ = std::fs::write(path, body);
}

/// Render a path the way Vim writes it: a leading `~` for paths under `$HOME`.
fn tildify(path: &Path, home: Option<&Path>) -> String {
    if let Some(home) = home {
        if let Ok(rest) = path.strip_prefix(home) {
            if rest.as_os_str().is_empty() {
                return "~".to_string();
            }
            return format!("~/{}", rest.to_string_lossy());
        }
    }
    path.to_string_lossy().into_owned()
}

/// Quote a string for a `|` bar line the way Vim's `barline_writestring` does:
/// wrap in double quotes and backslash-escape `"`, `\`, newline, and carriage
/// return.
fn bar_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

fn canon(path: &Path) -> PathBuf {
    std::fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf())
}

/// A register's stored values, newest first (empty if unset).
fn register_values(editor: &Editor, name: char) -> Vec<String> {
    editor
        .registers
        .read(name, editor)
        .map(|vals| vals.map(|v| v.into_owned()).collect())
        .unwrap_or_default()
}

fn render(editor: &Editor, ts: u64, home: Option<&Path>) -> String {
    let mut out = String::new();

    // Header + version + encoding (two trailing blank lines, as Vim writes).
    out.push_str("# This viminfo file was generated by zmax.\n");
    out.push_str("# You may edit it if you're careful!\n\n");
    out.push_str("# Viminfo version\n|1,4\n\n");
    out.push_str("# Value of 'encoding' when this file was written\n*encoding=utf-8\n\n\n");

    // hlsearch state (zmax has no persisted toggle; report off like a fresh Vim).
    out.push_str("# hlsearch on (H) or off (h):\n~h\n");

    // Last search pattern, if any. Flags mirror Vim's default magic search.
    if let Some(pat) = editor.registers.first('/', editor) {
        if !pat.is_empty() {
            out.push_str("# Last Search Pattern:\n");
            let _ = writeln!(out, "~MSle0~/{}", pat);
        }
    }
    out.push('\n');

    // Command Line History (the `:` register), newest to oldest.
    out.push_str("# Command Line History (newest to oldest):\n");
    for entry in register_values(editor, ':') {
        let _ = writeln!(out, ":{}", entry);
        let _ = writeln!(out, "|2,0,{},,{}", ts, bar_quote(&entry));
    }
    out.push('\n');

    // Search String History (the `/` register), newest to oldest.
    out.push_str("# Search String History (newest to oldest):\n");
    for entry in register_values(editor, '/') {
        let _ = writeln!(out, "?{}", entry);
        let _ = writeln!(out, "|2,1,{},,{}", ts, bar_quote(&entry));
    }
    out.push('\n');

    // zmax has no equivalents for these — emitted empty, exactly as Vim does.
    out.push_str("# Expression History (newest to oldest):\n\n");
    out.push_str("# Input Line History (newest to oldest):\n\n");
    out.push_str("# Debug Line History (newest to oldest):\n\n");

    // Registers — skip command/search history and the clipboard proxies.
    out.push_str("# Registers:\n");
    for name in editor.registers.written() {
        if matches!(name, ':' | '/' | '*' | '+') {
            continue;
        }
        let values = register_values(editor, name);
        // Split into physical lines so multi-line yanks render one `\t<line>` each.
        let lines: Vec<String> = values
            .iter()
            .flat_map(|v| v.split('\n'))
            .map(str::to_string)
            .collect();
        if lines.is_empty() {
            continue;
        }
        let _ = writeln!(out, "\"{}\tCHAR\t0", name);
        for line in &lines {
            let _ = writeln!(out, "\t{}", line);
        }
        let mut bar = format!("|3,0,{},0,{},0,{}", name as u32, lines.len(), ts);
        for line in &lines {
            bar.push(',');
            bar.push_str(&bar_quote(line));
        }
        out.push_str(&bar);
        out.push('\n');
    }
    out.push('\n');

    // Cursor position of every open buffer, keyed by canonical path, so file
    // marks can carry a real line/col when the file is currently open.
    let mut open_cursor: HashMap<PathBuf, (usize, usize)> = HashMap::new();
    for (view, _) in editor.tree.views() {
        if let Some(doc) = editor.document(view.doc) {
            if let Some(path) = doc.path() {
                let text = doc.text().slice(..);
                let pos = doc.selection(view.id).primary().cursor(text);
                let coords = coords_at_pos(text, pos);
                open_cursor.insert(canon(path), (coords.row + 1, coords.col));
            }
        }
    }

    // Per-file marks folded into each `> path` block below, keyed by canonical
    // path. Open buffers contribute their live letter/auto marks; the editor's
    // global marks (`A`-`Z`) contribute too — sourced here (not just from open
    // docs) so a global mark survives its file being closed.
    let mut file_marks: HashMap<PathBuf, std::collections::BTreeMap<char, (usize, usize)>> =
        HashMap::new();
    for doc in editor.documents() {
        let Some(path) = doc.path() else { continue };
        let text = doc.text().slice(..);
        let entry = file_marks.entry(canon(path)).or_default();
        for (m, pos) in doc.marks_iter() {
            let coords = coords_at_pos(text, pos);
            entry.insert(m, (coords.row + 1, coords.col));
        }
    }
    for (&m, gm) in &editor.global_marks {
        if m.is_ascii_uppercase() {
            file_marks
                .entry(canon(&gm.path))
                .or_default()
                .insert(m, (gm.line + 1, gm.col));
        }
    }
    file_marks.retain(|_, m| !m.is_empty());

    // The recent-files MRU list (newest first) drives both the numbered file
    // marks and the per-file `> path` blocks, mirroring how Vim records every
    // recently edited file.
    let recent = crate::recent_files::load();

    // File marks: the recent-files list maps to numbered marks `'0`..`'9`.
    out.push_str("# File marks:\n");
    for (i, path) in recent.iter().take(10).enumerate() {
        let mark = (b'0' + i as u8) as char;
        let (line, col) = open_cursor.get(&canon(path)).copied().unwrap_or((1, 0));
        let disp = tildify(path, home);
        let _ = writeln!(out, "'{}  {}  {}  {}", mark, line, col, disp);
        let _ = writeln!(
            out,
            "|4,{},{},{},{},{}",
            '0' as u32 + i as u32,
            line,
            col,
            ts,
            bar_quote(&disp)
        );
    }
    out.push('\n');

    // Jumplist of the focused view, newest first (Vim mark name `'`, code 39).
    out.push_str("# Jumplist (newest first):\n");
    if let Some(view) = editor.tree.try_get(editor.tree.focus) {
        for (doc_id, selection) in view.jumps.iter().rev() {
            if let Some(doc) = editor.document(*doc_id) {
                if let Some(path) = doc.path() {
                    let text = doc.text().slice(..);
                    let pos = selection.primary().cursor(text);
                    let coords = coords_at_pos(text, pos);
                    let disp = tildify(path, home);
                    let _ = writeln!(out, "-'  {}  {}  {}", coords.row + 1, coords.col, disp);
                    let _ = writeln!(
                        out,
                        "|4,39,{},{},{},{}",
                        coords.row + 1,
                        coords.col,
                        ts,
                        bar_quote(&disp)
                    );
                }
            }
        }
    }
    out.push('\n');

    // History of marks within files: one `> path` block per recently edited
    // file, newest first — exactly the list Vim records here, which is also how
    // recent-files consumers (e.g. fzf pickers) harvest the MRU set. Each block
    // carries the `*` last-used timestamp and the `"` last-cursor mark, plus any
    // letter/auto marks when the file is currently open.
    out.push_str("# History of marks within files (newest to oldest):\n");
    // Recent files first (newest to oldest), then any file that only carries a
    // global mark (so closed-file globals still get a block).
    let mut block_paths: Vec<PathBuf> = recent.iter().map(|p| canon(p)).collect();
    for cpath in file_marks.keys() {
        if !block_paths.contains(cpath) {
            block_paths.push(cpath.clone());
        }
    }
    for cpath in &block_paths {
        let (line, col) = open_cursor.get(cpath).copied().unwrap_or((1, 0));
        let disp = tildify(cpath, home);
        // The blank line before each block doubles as the blank after the header.
        let _ = writeln!(out, "\n> {}", disp);
        // The `*` mark is the file's last-used timestamp, not a position.
        let _ = writeln!(out, "\t*\t{}\t0", ts);
        // The `"` mark is the cursor position when last in this file.
        let _ = writeln!(out, "\t\"\t{}\t{}", line, col);
        if let Some(marks) = file_marks.get(cpath) {
            for (mark, (l, c)) in marks {
                if *mark == '"' {
                    continue;
                }
                let _ = writeln!(out, "\t{}\t{}\t{}", mark, l, c);
            }
        }
    }

    out
}

/// Read `.zmaxinfo` back into the vim global (`A`-`Z`) and numbered file
/// (`0`-`9`) marks, so they survive a restart. Numbered marks come from the
/// machine-readable `|4,<code>,…` File-marks bar lines (`'0'`..`'9'`, char codes
/// 48-57); global marks come from the uppercase entries of each `> path` block.
/// Returns an empty map when the file is absent or unreadable.
pub fn load() -> HashMap<char, zmax_view::GlobalMark> {
    let Ok(contents) = std::fs::read_to_string(store_path()) else {
        return HashMap::new();
    };
    parse(&contents, home_dir().as_deref())
}

/// Reverse of [`tildify`]: expand a leading `~` back to the home directory.
fn untildify(s: &str, home: Option<&Path>) -> PathBuf {
    match (s, home) {
        ("~", Some(home)) => home.to_path_buf(),
        (s, Some(home)) if s.starts_with("~/") => home.join(&s[2..]),
        _ => PathBuf::from(s),
    }
}

/// Reverse of [`bar_quote`]: strip the wrapping quotes and unescape.
fn bar_unquote(s: &str) -> String {
    let inner = s
        .strip_prefix('"')
        .and_then(|s| s.strip_suffix('"'))
        .unwrap_or(s);
    let mut out = String::with_capacity(inner.len());
    let mut chars = inner.chars();
    while let Some(ch) = chars.next() {
        if ch == '\\' {
            match chars.next() {
                Some('n') => out.push('\n'),
                Some('r') => out.push('\r'),
                Some(other) => out.push(other),
                None => {}
            }
        } else {
            out.push(ch);
        }
    }
    out
}

fn parse(contents: &str, home: Option<&Path>) -> HashMap<char, zmax_view::GlobalMark> {
    use zmax_view::GlobalMark;

    let mut marks: HashMap<char, GlobalMark> = HashMap::new();
    let mut cur_path: Option<PathBuf> = None;

    for line in contents.lines() {
        // `> path` opens a per-file mark block.
        if let Some(rest) = line.strip_prefix("> ") {
            cur_path = Some(untildify(rest.trim(), home));
            continue;
        }

        // File-marks bar line: `|4,<code>,<line>,<col>,<ts>,"<file>"`.
        if let Some(rest) = line.strip_prefix("|4,") {
            // 5 comma-separated fields: code, line, col, ts, "file". `splitn(5)`
            // keeps any commas in the (quoted) filename intact in the last field.
            let fields: Vec<&str> = rest.splitn(5, ',').collect();
            if fields.len() == 5 {
                if let (Ok(code), Ok(l), Ok(c)) = (
                    fields[0].parse::<u32>(),
                    fields[1].parse::<usize>(),
                    fields[2].parse::<usize>(),
                ) {
                    // Numbered file marks '0'-'9' (codes 48-57); code 39 is the
                    // jumplist and any other code is not a persisted mark.
                    if (48..=57).contains(&code) {
                        if let Some(mark) = char::from_u32(code) {
                            marks.insert(
                                mark,
                                GlobalMark {
                                    path: untildify(&bar_unquote(fields[4]), home),
                                    line: l.saturating_sub(1),
                                    col: c,
                                },
                            );
                        }
                    }
                }
            }
            continue;
        }

        // Uppercase marks inside a `> path` block: `\t<mark>\t<line>\t<col>`.
        if let (Some(path), Some(rest)) = (&cur_path, line.strip_prefix('\t')) {
            let parts: Vec<&str> = rest.split('\t').collect();
            if parts.len() == 3 && parts[0].chars().count() == 1 {
                let mark = parts[0].chars().next().unwrap();
                if mark.is_ascii_uppercase() {
                    if let (Ok(l), Ok(c)) = (parts[1].parse::<usize>(), parts[2].parse::<usize>()) {
                        marks.insert(
                            mark,
                            GlobalMark {
                                path: path.clone(),
                                line: l.saturating_sub(1),
                                col: c,
                            },
                        );
                    }
                }
            }
        }
    }

    marks
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bar_quote_escapes_specials() {
        assert_eq!(bar_quote("q"), "\"q\"");
        assert_eq!(bar_quote("a\"b"), "\"a\\\"b\"");
        assert_eq!(bar_quote("a\\b"), "\"a\\\\b\"");
        assert_eq!(bar_quote("a\nb"), "\"a\\nb\"");
    }

    #[test]
    fn tildify_collapses_home() {
        let home = Path::new("/Users/me");
        assert_eq!(
            tildify(Path::new("/Users/me/.zshrc"), Some(home)),
            "~/.zshrc"
        );
        assert_eq!(tildify(Path::new("/Users/me"), Some(home)), "~");
        assert_eq!(tildify(Path::new("/etc/hosts"), Some(home)), "/etc/hosts");
        assert_eq!(tildify(Path::new("/etc/hosts"), None), "/etc/hosts");
    }

    #[test]
    fn untildify_reverses_tildify() {
        let home = Path::new("/Users/me");
        assert_eq!(
            untildify("~/.zshrc", Some(home)),
            Path::new("/Users/me/.zshrc")
        );
        assert_eq!(untildify("~", Some(home)), Path::new("/Users/me"));
        assert_eq!(untildify("/etc/hosts", Some(home)), Path::new("/etc/hosts"));
        // No home: a leading `~` is left untouched.
        assert_eq!(untildify("~/x", None), Path::new("~/x"));
    }

    #[test]
    fn bar_unquote_reverses_bar_quote() {
        for s in ["q", "a\"b", "a\\b", "a\nb", "a\rb", "with,comma"] {
            assert_eq!(bar_unquote(&bar_quote(s)), s, "round-trip failed for {s:?}");
        }
    }

    #[test]
    fn parse_extracts_numbered_and_global_marks() {
        let home = Path::new("/Users/me");
        // Mirrors the writer's output: a File-marks bar line for `'0`, plus a
        // `> path` block carrying an uppercase global mark `A` and a lowercase
        // `a` mark (which must be ignored — lowercase marks stay buffer-local).
        let info = "\
# File marks:
'0  12  4  ~/src/main.rs
|4,48,12,4,1700000000,\"~/src/main.rs\"

# History of marks within files (newest to oldest):

> ~/src/lib.rs
\t*\t1700000000\t0
\t\"\t7\t2
\tA\t7\t2
\ta\t9\t0
";
        let marks = parse(info, Some(home));

        let numbered = marks.get(&'0').expect("numbered mark '0' restored");
        assert_eq!(numbered.path, Path::new("/Users/me/src/main.rs"));
        assert_eq!((numbered.line, numbered.col), (11, 4)); // 1-based line 12 -> 0-based 11

        let global = marks.get(&'A').expect("global mark 'A' restored");
        assert_eq!(global.path, Path::new("/Users/me/src/lib.rs"));
        assert_eq!((global.line, global.col), (6, 2)); // 1-based line 7 -> 0-based 6

        // Lowercase and the auto `"` mark are not global marks.
        assert!(!marks.contains_key(&'a'));
        assert!(!marks.contains_key(&'"'));
    }
}
