// Generated from port/data/vim_options.json — the full Vim/Neovim :set option
// surface (name, is_boolean, default value). Used by `:set` / `:set all` /
// `:set opt?` so every option round-trips even without a behavioral effect.
// (name, is_bool, default)
pub const VIM_OPTION_TABLE: &[(&str, bool, &str)] = &[
    ("allowrevins", true, "off"),
    ("ambiwidth", false, "single"),
    ("arabic", true, "off"),
    ("arabicshape", true, "on"),
    ("autochdir", true, "off"),
    ("autocomplete", true, "off"),
    ("autocompletedelay", false, "0"),
    ("autocompletetimeout", false, "80"),
    ("autoindent", true, "on"),
    ("autoread", true, "on"),
    ("autowrite", true, "off"),
    ("autowriteall", true, "off"),
    ("background", false, "dark"),
    ("backspace", false, "indent,eol,start"),
    ("backup", true, "off"),
    ("backupcopy", false, "auto"),
    ("backupdir", false, ".,$XDG_STATE_HOME/nvim/backup//"),
    ("backupext", false, "~"),
    ("backupskip", false, ""),
    ("belloff", false, "all"),
    ("binary", true, "off"),
    ("bomb", true, "off"),
    ("breakat", false, " ^I!@*-+;:,./?"),
    ("breakindent", true, "off"),
    ("breakindentopt", false, ""),
    ("bufhidden", false, ""),
    ("buflisted", true, "on"),
    ("buftype", false, ""),
    ("busy", false, "0"),
    ("casemap", false, "internal,keepascii"),
    ("cdhome", true, "on"),
    ("cdpath", false, "equivalent to $CDPATH or \",,\""),
    ("cedit", false, "CTRL-F"),
    ("channel", false, "0"),
    ("charconvert", false, ""),
    ("chistory", false, "10"),
    ("cindent", true, "off"),
    ("cinkeys", false, "\"0{,0},0"),
    ("cinoptions", false, ""),
    ("cinscopedecls", false, "public,protected,private"),
    ("cinwords", false, "if,else,while,do,for,switch"),
    ("clipboard", false, ""),
    ("cmdheight", false, "1"),
    ("cmdwinheight", false, "7"),
    ("colorcolumn", false, ""),
    ("columns", false, "80 or terminal width"),
    (
        "comments",
        false,
        "s1:/*,mb:*,ex:*/,://,b:#,:%,:XCOMM,n:>,fb:-,fb:•",
    ),
    ("commentstring", false, ""),
    ("complete", false, ".,w,b,u,t"),
    ("completefunc", false, ""),
    ("completeitemalign", false, "abbr,kind,menu"),
    ("completeopt", false, "menu,popup"),
    ("completeslash", false, ""),
    ("completetimeout", false, "0"),
    ("concealcursor", false, ""),
    ("conceallevel", false, "0"),
    ("confirm", true, "off"),
    ("copyindent", true, "off"),
    ("cpoptions", false, "aABceFs_"),
    ("cursorbind", true, "off"),
    ("cursorcolumn", true, "off"),
    ("cursorline", true, "off"),
    ("cursorlineopt", false, "both"),
    ("debug", false, ""),
    ("define", false, ""),
    ("delcombine", true, "off"),
    ("dictionary", false, ""),
    ("diff", true, "off"),
    ("diffanchors", false, ""),
    ("diffexpr", false, ""),
    (
        "diffopt",
        false,
        "internal,filler,closeoff,indent-heuristic,inline:char,linematch:40",
    ),
    ("digraph", true, "off"),
    ("directory", false, "$XDG_STATE_HOME/nvim/swap//"),
    ("display", false, "lastline"),
    ("eadirection", false, "both"),
    ("emoji", true, "on"),
    ("encoding", false, "utf-8"),
    ("endoffile", true, "off"),
    ("endofline", true, "on"),
    ("equalalways", true, "on"),
    ("equalprg", false, ""),
    ("errorbells", true, "off"),
    ("errorfile", false, "errors.err"),
    ("errorformat", false, "is very long"),
    ("eventignore", false, ""),
    ("eventignorewin", false, ""),
    ("expandtab", true, "off"),
    ("exrc", true, "off"),
    ("fileencoding", false, ""),
    ("fileencodings", false, "ucs-bom,utf-8,default,latin1"),
    ("fileformat", false, "Windows: \"dos\", Unix: \"unix\""),
    (
        "fileformats",
        false,
        "Windows: \"dos,unix\", Unix: \"unix,dos\"",
    ),
    ("fileignorecase", true, "off"),
    ("filetype", false, ""),
    ("fillchars", false, ""),
    ("findfunc", false, ""),
    ("fixendofline", true, "on"),
    ("foldclose", false, ""),
    ("foldcolumn", false, "0"),
    ("foldenable", true, "on"),
    ("foldexpr", false, "0"),
    ("foldignore", false, "#"),
    ("foldlevel", false, "0"),
    ("foldlevelstart", false, "-1"),
    ("foldmarker", false, "{{{,}}}"),
    ("foldmethod", false, "manual"),
    ("foldminlines", false, "1"),
    ("foldnestmax", false, "20"),
    (
        "foldopen",
        false,
        "block,hor,mark,percent,quickfix,search,tag,undo",
    ),
    ("foldtext", false, "\"foldtext("),
    ("formatexpr", false, ""),
    ("formatlistpat", false, "\"^\\s*\\d\\+[\\]:."),
    ("formatoptions", false, "tcqj"),
    ("formatprg", false, ""),
    ("fsync", true, "on"),
    ("grepformat", false, "%f:%l:%m,%f:%l%m,%f %l%m"),
    ("grepprg", false, "see below"),
    (
        "guicursor",
        false,
        "n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20,t:block-blinkon500-blinkoff500-TermCursor",
    ),
    ("guifont", false, ""),
    ("guifontwide", false, ""),
    ("helpfile", false, "(MS-Windows"),
    ("helpheight", false, "20"),
    ("helplang", false, "messages language or empty"),
    ("hidden", true, "on"),
    ("history", false, "10000"),
    ("hlsearch", true, "on"),
    ("icon", true, "off"),
    ("iconstring", false, ""),
    ("ignorecase", true, "off"),
    ("iminsert", false, "0"),
    ("imsearch", false, "-1"),
    ("inccommand", false, "nosplit"),
    ("include", false, ""),
    ("includeexpr", false, ""),
    ("incsearch", true, "on"),
    ("indentexpr", false, ""),
    ("indentkeys", false, "\"0{,0},0"),
    ("infercase", true, "off"),
    ("isfname", false, ""),
    ("isident", false, ""),
    ("iskeyword", false, "@,48-57,_,192-255"),
    ("isprint", false, "@,161-255"),
    ("joinspaces", true, "off"),
    ("jumpoptions", false, "clean"),
    ("keymap", false, ""),
    ("keymodel", false, ""),
    ("keywordprg", false, ":Man\", Windows: \":help"),
    ("langmap", false, ""),
    ("langmenu", false, ""),
    ("langremap", true, "off"),
    ("laststatus", false, "2"),
    ("lazyredraw", true, "off"),
    ("lhistory", false, "10"),
    ("linebreak", true, "off"),
    ("lines", false, "24 or terminal height"),
    ("linespace", false, "0"),
    ("lisp", true, "off"),
    ("lispoptions", false, ""),
    ("lispwords", false, "is very long"),
    ("list", true, "off"),
    ("listchars", false, "tab:> ,trail:-,nbsp:+"),
    ("loadplugins", true, "on"),
    ("makeef", false, ""),
    ("makeencoding", false, ""),
    ("makeprg", false, "make"),
    ("matchpairs", false, "\"(:"),
    ("matchtime", false, "5"),
    ("maxfuncdepth", false, "100"),
    ("maxmapdepth", false, "1000"),
    ("maxmempattern", false, "1000"),
    ("maxsearchcount", false, "999"),
    ("menuitems", false, "25"),
    ("messagesopt", false, "hit-enter,history:500,progress:c"),
    ("mkspellmem", false, "460000,2000,500"),
    ("modeline", true, "on"),
    ("modelineexpr", true, "off"),
    ("modelines", false, "5"),
    ("modifiable", true, "on"),
    ("modified", true, "off"),
    ("more", true, "on"),
    ("mouse", false, "nvi"),
    ("mousefocus", true, "off"),
    ("mousehide", true, "on"),
    ("mousemodel", false, "popup_setpos"),
    ("mousemoveevent", true, "off"),
    ("mousescroll", false, "ver:3,hor:6"),
    ("mousetime", false, "500"),
    ("nrformats", false, "bin,hex"),
    ("number", true, "off"),
    ("numberwidth", false, "4"),
    ("omnifunc", false, ""),
    ("operatorfunc", false, ""),
    ("packpath", false, "see 'runtimepath'"),
    ("paragraphs", false, "IPLPPPQPP TPHPLIPpLpItpplpipbp"),
    ("patchexpr", false, ""),
    ("patchmode", false, ""),
    ("path", false, ".,,"),
    ("preserveindent", true, "off"),
    ("previewheight", false, "12"),
    ("previewwindow", true, "off"),
    ("pumblend", false, "0"),
    ("pumborder", false, ""),
    ("pumheight", false, "0"),
    ("pummaxwidth", false, "0"),
    ("pumwidth", false, "15"),
    ("pyxversion", false, "3"),
    ("quickfixtextfunc", false, ""),
    ("quoteescape", false, "\\"),
    ("readonly", true, "off"),
    ("redrawdebug", false, ""),
    ("redrawtime", false, "2000"),
    ("regexpengine", false, "0"),
    ("relativenumber", true, "off"),
    ("report", false, "2"),
    ("revins", true, "off"),
    ("rightleft", true, "off"),
    ("rightleftcmd", false, "search"),
    ("ruler", true, "on"),
    ("rulerformat", false, ""),
    ("runtimepath", false, ""),
    ("scroll", false, "half the window height"),
    ("scrollback", false, "10000"),
    ("scrollbind", true, "off"),
    ("scrolljump", false, "1"),
    ("scrolloff", false, "0"),
    ("scrolloffpad", false, "0"),
    ("scrollopt", false, "ver,jump"),
    ("sections", false, "SHNHH HUnhsh"),
    ("selection", false, "inclusive"),
    ("selectmode", false, ""),
    (
        "sessionoptions",
        false,
        "blank,buffers,curdir,folds,help,tabpages,winsize,terminal",
    ),
    ("shada", false, "!,'100,<50,s10,h,r/tmp/,r/private/"),
    ("shadafile", false, ""),
    ("shell", false, "$SHELL or \"sh\", Win32: \"cmd.exe\""),
    ("shellcmdflag", false, ""),
    (
        "shellpipe",
        false,
        ">\", \"| tee\", \"|& tee\" or \"2>&1| tee",
    ),
    ("shellquote", false, ""),
    ("shellredir", false, ">\", \">&\" or \">%s 2>&1"),
    ("shellslash", true, "off"),
    ("shelltemp", true, "off"),
    ("shellxescape", false, ""),
    ("shellxquote", false, ""),
    ("shiftround", true, "off"),
    ("shiftwidth", false, "8"),
    ("shortmess", false, "ltToOCF"),
    ("showbreak", false, ""),
    ("showcmd", true, "on"),
    ("showcmdloc", false, "last"),
    ("showfulltag", true, "off"),
    ("showmatch", true, "off"),
    ("showmode", true, "on"),
    ("showtabline", false, "1"),
    ("sidescroll", false, "1"),
    ("sidescrolloff", false, "0"),
    ("signcolumn", false, "auto"),
    ("smartcase", true, "off"),
    ("smartindent", true, "off"),
    ("smarttab", true, "on"),
    ("smoothscroll", true, "off"),
    ("softtabstop", false, "0"),
    ("spell", true, "off"),
    ("spellcapcheck", false, "\"[.?!]\\_[\\]"),
    ("spellfile", false, ""),
    ("spelllang", false, "en"),
    ("spelloptions", false, ""),
    ("spellsuggest", false, "best"),
    ("splitbelow", true, "off"),
    ("splitkeep", false, "cursor"),
    ("splitright", true, "off"),
    ("startofline", true, "off"),
    ("statuscolumn", false, ""),
    ("statusline", false, "is very long"),
    ("suffixes", false, ".bak,~,.o,.h,.info,.swp,.obj"),
    ("suffixesadd", false, ""),
    ("swapfile", true, "on"),
    ("switchbuf", false, "uselast"),
    ("synmaxcol", false, "3000"),
    ("syntax", false, ""),
    ("tabclose", false, ""),
    ("tabline", false, ""),
    ("tabpagemax", false, "50"),
    ("tabstop", false, "8"),
    ("tagbsearch", true, "on"),
    ("tagcase", false, "followic"),
    ("tagfunc", false, ""),
    ("taglength", false, "0"),
    ("tagrelative", true, "on"),
    ("tags", false, "./tags;,tags"),
    ("tagstack", true, "on"),
    ("termbidi", true, "off"),
    ("termguicolors", true, "off"),
    ("termpastefilter", false, "BS,HT,ESC,DEL"),
    ("termsync", true, "on"),
    ("textwidth", false, "0"),
    ("thesaurus", false, ""),
    ("thesaurusfunc", false, ""),
    ("tildeop", true, "off"),
    ("timeout", true, "on"),
    ("timeoutlen", false, "1000"),
    ("title", true, "off"),
    ("titlelen", false, "85"),
    ("titleold", false, ""),
    ("titlestring", false, ""),
    ("ttimeout", true, "on"),
    ("ttimeoutlen", false, "50"),
    ("ttyfast", true, "on"),
    ("undodir", false, "$XDG_STATE_HOME/nvim/undo//"),
    ("undofile", true, "off"),
    ("undolevels", false, "1000"),
    ("undoreload", false, "10000"),
    ("updatecount", false, "200"),
    ("updatetime", false, "4000"),
    ("varsofttabstop", false, ""),
    ("vartabstop", false, ""),
    ("verbose", false, "0"),
    ("verbosefile", false, ""),
    ("viewdir", false, "$XDG_STATE_HOME/nvim/view//"),
    ("viewoptions", false, "folds,cursor,curdir"),
    ("virtualedit", false, ""),
    ("visualbell", true, "off"),
    ("warn", true, "on"),
    ("whichwrap", false, "b,s"),
    ("wildchar", false, "<Tab>"),
    ("wildcharm", false, "0"),
    ("wildignore", false, ""),
    ("wildignorecase", true, "off"),
    ("wildmenu", true, "on"),
    ("wildmode", false, "full"),
    ("wildoptions", false, "pum,tagfile"),
    ("winaltkeys", false, "menu"),
    ("winbar", false, ""),
    ("winblend", false, "0"),
    ("winborder", false, ""),
    ("window", false, "screen height - 1"),
    ("winfixbuf", true, "off"),
    ("winfixheight", true, "off"),
    ("winfixwidth", true, "off"),
    ("winheight", false, "1"),
    ("winhighlight", false, ""),
    ("winminheight", false, "1"),
    ("winminwidth", false, "1"),
    ("winpinned", true, "off"),
    ("winwidth", false, "20"),
    ("wrap", true, "on"),
    ("wrapmargin", false, "0"),
    ("wrapscan", true, "on"),
    ("write", true, "on"),
    ("writeany", true, "off"),
    ("writebackup", true, "on"),
    ("writedelay", false, "0"),
];
