[book]
authors = ["MenkeTechnologies"]
language = "en"
src = "src"

[output.html]
default-theme = "colibri"
preferred-dark-theme = "colibri"
git-repository-url = "https://github.com/MenkeTechnologies/zmax"
edit-url-template = "https://github.com/MenkeTechnologies/zmax/edit/main/book/{path}"
additional-css = ["custom.css"]
additional-js = ["ts-query.js", "version.js"]

[output.html.search]
use-boolean-and = true
